### ISSUE TITLE
[Bug]: I/O error reading PNG header!

### ISSUE THREAD

**Issue by RMuetterlein** [mallowigi/material-theme-issues#103]
### Describe the bug

Error on start PHPStorm 2021.3.2

### To Reproduce

Open PHPStorm 2021.3.2

### Expected behavior

Open PHPStorm 2021.3.2

### Material Theme Version

5.5.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2021.3.2
Build #PS-213.6777.58, built on January 31, 2022
Licensed to B3 IT Systeme GmbH / René Mütterlein
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2022.
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2032M
Cores: 4
Registry:
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.5.1)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    in.thekalinga.snippet.intellij (6.1.0)
    mobi.hsz.idea.gitignore (4.3.0)
    de.netnexus.camelcaseplugin (3.0.12)
    com.mallowigi.imageicon (13.0)
    com.intellij.ideolog (203.0.27.0)
    com.wix.sasslint (1.1.2)
    com.wix.scss.lint (2.1.1)
    com.alicannklc.tailwind (1.4.6)
    DBN (3.3.1555.0)
    net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
    de.espend.idea.php.toolbox (6.0.0)
    de.espend.idea.php.annotation (8.0.0)
    fr.adrienbrault.idea.symfony2plugin (0.23.213)
    Magicento (3.1.7)
    ru.adelf.idea.dotenv (2022.1)
```

### Logs/Screenshots

```shell
javax.imageio.IIOException: I/O error reading PNG header!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:318)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:701)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1398)
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1813)
	at com.intellij.util.ImageLoader.loadPng(ImageLoader.java:352)
	at com.intellij.util.ImageLoader.loadFromStream(ImageLoader.java:553)
	at com.intellij.util.ImageLoader.loadFromBytes(ImageLoader.java:544)
	at com.mallowigi.imageicon.converters.RegularImageConverter$Companion.loadImageIcon(RegularImageConverter.kt:111)
	at com.mallowigi.imageicon.converters.RegularImageConverter$Companion.access$loadImageIcon(RegularImageConverter.kt:101)
	at com.mallowigi.imageicon.converters.RegularImageConverter.convert(RegularImageConverter.kt:67)
	at com.mallowigi.imageicon.ImageIconProvider.getIcon(ImageIconProvider.kt:44)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:247)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:172)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:99)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:96)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:171)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.imageio.IIOException: Bad PNG signature!
	at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:245)
	... 52 more
```

**Comment by mallowigi** [comment]
Related to the image loader plugin, wrong repository.
