### ISSUE TITLE
[Bug]: Navigation Bar stop working

### ISSUE THREAD

**Issue by Alejandrom3** [mallowigi/material-theme-issues#132]
### Describe the bug

After updating the material theme plugin, the navigation bar (the one which shows the file path of the current file) stop showing. If i disable the plugin, it shows again.

### To Reproduce

1. Open WebStorm
2. Update Plugin
3. Doesn't show navigation Bar
4. The project button at the bottom when clicked show an error

### Expected behavior

Show the navigation Bar below the main menu and in the footer section of the IDE
![image](https://user-images.githubusercontent.com/10180045/162843662-eb8e1f4e-313e-45f5-8089-f1d4817af436.png)

It should show this:
![image](https://user-images.githubusercontent.com/10180045/162843796-86436778-72f4-4b37-8940-d4458ee4563c.png)

![image](https://user-images.githubusercontent.com/10180045/162846762-d669fa4a-4053-4e79-b01d-b7e684ee6128.png)

### Material Theme Version

v7.3.0

### IDE

WebStorm

### System Info

```shell
OS - Linux
IDE - Webstorm 2022.1
Plugin version: 3.7.0
```

### Logs/Screenshots

```shell
com.intellij.util.IncorrectOperationException: Sorry but parent: com.intellij.ide.navigationToolbar.NavBarPanel[,0,0,1662x32,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.components.JBViewport$ResourceViewBorder@5ed7e9ff,flags=16777217,maximumSize=,minimumSize=,preferredSize=] (class com.intellij.ide.navigationToolbar.NavBarPanel) has already been disposed (see the cause for stacktrace) so the child:  (class com.intellij.ide.navigationToolbar.NavBarItem) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:76)
	at com.intellij.ide.navigationToolbar.NavBarItem.<init>(NavBarItem.java:111)
	at com.intellij.ide.navigationToolbar.NavBarPopup.lambda$createPopupContent$4(NavBarPopup.java:179)
	at com.intellij.ui.components.SelectionAwareListCellRenderer.getListCellRendererComponent(SelectionAwareListCellRenderer.java:24)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:304)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1683)
	at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:179)
	at com.intellij.ide.navigationToolbar.NavBarListWrapper.<init>(NavBarListWrapper.java:64)
	at com.intellij.ide.navigationToolbar.NavBarPopup.createPopupContent(NavBarPopup.java:189)
	at com.intellij.ide.navigationToolbar.NavBarPopup.<init>(NavBarPopup.java:44)
	at com.intellij.ide.navigationToolbar.NavBarPanel.ctrlClick(NavBarPanel.java:624)
	at com.intellij.ide.navigationToolbar.NavBarPanel$2.click(NavBarPanel.java:520)
	at com.intellij.ide.navigationToolbar.NavBarPanel$2.mousePressed(NavBarPanel.java:489)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
Please don't report bugs for the experimental new ui.
