### ISSUE TITLE
[Bug]: Exiting presentation mode throws an exception

### ISSUE THREAD

**Issue by jmatias** [mallowigi/material-theme-issues#146]
### Describe the bug

When exiting presentation mode, the font size does not revert back to the original size. When when I try to fix the font size manually, the plugin throws the following exception:

```stack trace

Boolean getter 'isUseMaterialFont2' not found in com.mallowigi.idea.config.application.MTConfig@638f9f7a

java.lang.NoSuchMethodException: no such method: com.mallowigi.idea.config.application.MTConfig.isUseMaterialFont2()boolean/invokeVirtual
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:963)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
       ...
```

<details> <summary><b><u>Click here to expand stack trace trace</u></b></summary>
<p>

```stacktrace

Boolean getter 'isUseMaterialFont2' not found in com.mallowigi.idea.config.application.MTConfig@638f9f7a

java.lang.NoSuchMethodException: no such method: com.mallowigi.idea.config.application.MTConfig.isUseMaterialFont2()boolean/invokeVirtual
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:963)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:1194)
	at com.intellij.ide.ui.PublicMethodBasedOptionDescription.isOptionEnabled(PublicMethodBasedOptionDescription.java:54)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:850)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:81)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:304)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:670)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2743)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at com.intellij.ide.actions.searcheverywhere.MixedSearchListModel.addElements(MixedSearchListModel.java:50)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListener.elementsAdded(SearchEverywhereUI.java:1159)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$0(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$2(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper$Buffer.flush(ThrottlingListenerWrapper.java:131)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.searchFinished(ThrottlingListenerWrapper.java:69)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$searchFinished$6(MixedResultsSearcher.java:334)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$8(MixedResultsSearcher.java:370)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoSuchMethodError: 'boolean com.mallowigi.idea.config.application.MTConfig.isUseMaterialFont2()'
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 55 more
```

</p>
</details>

### To Reproduce

1. Enter presentation mode

![image](https://user-images.githubusercontent.com/1302269/165695260-1ea9cb69-d9b4-4517-a768-bd0f03d506a3.png)

![image](https://user-images.githubusercontent.com/1302269/165695313-48e281f6-6ea3-4f3c-8a2a-1cfb53fbb840.png)

2. Exit presentation mode

![image](https://user-images.githubusercontent.com/1302269/165695526-6a54499a-3c89-4f0a-be22-fe1a9b943876.png)

![image](https://user-images.githubusercontent.com/1302269/165695693-5f6f51e0-f330-4f52-b640-11bebd1e6ef1.png)

### Expected behavior

Font sizes should go back to normal, but they don't.

![image](https://user-images.githubusercontent.com/1302269/165695693-5f6f51e0-f330-4f52-b640-11bebd1e6ef1.png)

When I try to jump to font settings, the plugin throws an exception.

![image](https://user-images.githubusercontent.com/1302269/165695872-6027df73-99ef-48f7-93d7-97b14d594577.png)

![image](https://user-images.githubusercontent.com/1302269/165696094-bc26f89d-9e2e-4a07-827e-6078357adb27.png)

### Material Theme Version

v7.3.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8000M
Cores: 10
Registry:
    actionSystem.cache.data=false
    ide.mac.transparentTitleBarAppearance=false
    ide.balloon.shadow.size=0
    scala.erase.compiler.process.jdk.once=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    some.awesome (1.14)
    ski.chrzanow.foldableprojectview (1.1.2)
    org.jetbrains.plugins.rest (221.5080.126)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (221.5080.126)
    hu.hawser.co-author-plugin (2.3)
    de.netnexus.camelcaseplugin (3.0.12)
    com.jetbrains.plugins.ini4idea (221.5080.126)
    com.intellij.plugins.macoskeymap (221.5080.106)
    com.intellij.nativeDebug (221.5080.218)
    com.intellij.ideolog (203.0.28.1)
    org.jetbrains.plugins.ruby (221.5080.169)
    com.intellij.properties.bundle.editor (221.5080.216)
    org.jetbrains.jumpToLine (0.1.8)
    com.intellij.guice (221.5080.169)
    com.github.shiraji.ccch (1.0.1)
    com.github.leomillon.uuidgenerator (4.5.1)
    String Manipulation (9.4.0)
    Shifter (1.9.6)
    Keymap exporter (2.2)
    mobi.hsz.idea.gitignore (4.4.0)
    com.mallowigi (64.0.0)
    FrameSwitcher (3.30.0-212)
    com.intellij.kubernetes (221.5080.240)
    com.intellij.tide (221.5080.240)
    Pythonid (221.5080.212)
    ru.meanmail.plugin.requirements (2022.3-2022.1)
    ru.adelf.idea.dotenv (2022.1)
    zielu.gittoolbox (212.8.9)
    org.intellij.scala (2022.1.592)
    izhangzhihao.rainbow.brackets (6.21)
    pro.bashsupport (2.1.7.221)
    com.intellij.bigdatatools (221.4165.63)
    com.chrisrm.idea.MaterialThemeUI (7.3.2)
    lermitage.intellij.extra.icons (2022.1.2)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

**Comment by mallowigi** [comment]
Thanks. Will be fixed next version
