### ISSUE TITLE
[Bug]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by petr-nehez** [mallowigi/material-theme-issues#148]
### Describe the bug

On opening of IDE

### To Reproduce

Have no idea

### Expected behavior

No error

### Material Theme Version

v7.3.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10500M
Cores: 12
Registry:
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    zielu.cleansheet (211.3.0)
    varme.pw.oceanic-dark-theme (1.1.2)
    ski.chrzanow.foldableprojectview (1.1.2)
    rasarts.espresso.light.theme (1.2.0)
    org.turbanov.run.configuration.as.action (1.4.5)
    org.dandoh.favacts (0.0.3)
    nix-idea (0.4.0.3)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (221.5080.126)
    lermitage.intellij.iconviewer (1.14.0.193)
    lermitage.intellij.extra.icons (2022.1.2)
    hunspell (221.5080.126)
    de.santiv.fastscrolling (1.2)
    de.ehmkah.projects.imgdiff (1.11.0)
    com.wakatime.intellij.plugin (13.1.14)
    com.tabnine.TabNine (0.6.0)
    com.layoutmanager (1.4.0)
    com.khmelyuk.multirun (1.13)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    com.intellij.plugins.watcher (221.5080.126)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    com.intellij.nativeDebug (221.5080.218)
    com.intellij.javafx (1.0.4)
    com.intellij.ideolog (203.0.28.1)
    com.wix.sasslint (1.1.2)
    com.github.today-.theme.spaceday (1.12)
    com.github.setial (4.0.2)
    com.github.l0drex.intellijkdebreezetheme (0.3.1)
    com.github.beansoftapp.visualgc.plugin (2022.1.0)
    ch.raffael.idea.plugins.runpopup (1.3.0)
    com.intellij.javaee.ejb (221.5080.169)
    com.intellij.selenium (221.5080.154)
    VisualVMLauncher (1.21.211.6085.0)
    String Manipulation (9.4.0)
    PsiViewer (221-SNAPSHOT)
    Key Promoter X (2022.1.1)
    JFormDesigner-Marketplace-Edition (7.0.5.4)
    GrepConsole (12.12.211.6693.0)
    zielu.gittoolbox (212.8.9)
    org.sonarlint.idea (6.7.0.45926)
    mobi.hsz.idea.gitignore (4.4.0)
    com.majera.intellij.codereview.bitbucket (2022.1.2.221)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    CheckStyle-IDEA (5.66.0)
    Batch Scripts Support (1.0.13)
    com.github.beansoft.devkit.helper (2022.1.0)
    org.rust.lang (0.4.169.4584-221)
    com.intellij.plugins.html.instantEditing (221.5080.169)
    izhangzhihao.rainbow.brackets (6.22)
    pro.bashsupport (2.1.7.221)
    com.intellij.bigdatatools (221.4165.63)
    com.haulmont.jpab (2022.2.2-221)
    com.chrisrm.idea.MaterialThemeUI (7.3.2)

Kotlin: 221-1.6.20-release-285-IJ5080.210
```

### Logs/Screenshots

```shell
java.lang.NullPointerException
	at com.mallowigi.idea.wizard.steps.MTWizardOtherOptionsPanel.setupComponents(MTWizardOtherOptionsPanel.java:88)
	at com.mallowigi.idea.wizard.steps.MTWizardOtherOptionsPanel.<init>(MTWizardOtherOptionsPanel.java:83)
	at com.mallowigi.idea.wizard.MTWizardStepsProvider.initSteps(MTWizardStepsProvider.kt:52)
	at com.intellij.ide.customize.CustomizeIDEWizardDialog.<init>(CustomizeIDEWizardDialog.java:58)
	at com.intellij.ide.customize.CustomizeIDEWizardDialog.<init>(CustomizeIDEWizardDialog.java:49)
	at com.mallowigi.idea.wizard.MTWizardDialog.<init>(MTWizardDialog.kt:44)
	at com.mallowigi.idea.MTApplicationComponent.initWizard$lambda-1(MTApplicationComponent.kt:69)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at com.intellij.cloudConfig.CloudConfigManager.waitDone(CloudConfigManager.java:1859)
	at com.intellij.cloudConfig.CloudConfigManager.getRepositoryPlugins(CloudConfigManager.java:1828)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$updatePlugins$43(CloudConfigManager.java:1931)
	at com.intellij.cloudConfig.CloudConfigManager.mergePlugins(CloudConfigManager.java:2101)
	at com.intellij.cloudConfig.CloudConfigManager.mergePlugins(CloudConfigManager.java:2092)
	at com.intellij.cloudConfig.CloudConfigManager.updatePlugins(CloudConfigManager.java:1927)
	at com.intellij.cloudConfig.CloudConfigManager.safeUpdatePlugins(CloudConfigManager.java:1868)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$doConnection$20(CloudConfigManager.java:1007)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
should be fixed in the next version
