### ISSUE TITLE
[Bug]: PHPStorm crashes when trying to commit to GIT using the sidebar

### ISSUE THREAD

**Issue by chrisneal** [mallowigi/material-theme-issues#188]
### Describe the bug

When trying to commit to GIT and PHPStorm loading the preview, PHPStorm hangs and crashes.

java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/MTHackLafProvider.getLookAndFeelInfo must not return null

### To Reproduce

I can replicate it everytime, but only with a single project. Other projects of mine DO NOT have the same issue.

1) Make a change to a file.
2) Open the Commit sidebar.
3) Click on one of the staged files.

### Expected behavior

The IDE should not crash.

### Material Theme Version

7.5.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.1.2
Build #PS-221.5787.33, built on June 1, 2022
Licensed to Chris Neal
Subscription is active until June 29, 2022.
Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    run.processes.with.pty=TRUE
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.sylfra.idea.plugins.linessorter (1.0.1)
    org.intellij.plugins.hcl (221.5787.20)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    name.kropp.intellij.makefile (221.5787.15)
    com.mroche.JsonHelper (1.1.2)
    com.intellij.lang.liquid (221.5787.15)
    com.intellij.ideolog (203.0.30.0)
    Key Promoter X (2022.2)
    mobi.hsz.idea.gitignore (4.4.0)
    de.espend.idea.php.annotation (8.2.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.aurimasniekis.phppsr4namespacedetector (1.0.1)
    intellij.prettierJS (221.5787.15)
    com.intellij.lang.jsgraphql (3.1.4)
    com.dmarcotte.handlebars (221.5787.37)
    com.chrisrm.idea.MaterialThemeUI (7.5.1)
    com.mallowigi (64.0.0)
    com.codestream.jetbrains-codestream (13.0.2+234)
    ru.adelf.idea.dotenv (2022.1)
    com.laravel_idea.plugin (5.4.0.221)
```

### Logs/Screenshots

```shell
java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/MTHackLafProvider.getLookAndFeelInfo must not return null
	at com.mallowigi.idea.MTHackLafProvider.$$$reportNull$$$0(MTHackLafProvider.java)
	at com.mallowigi.idea.MTHackLafProvider.getLookAndFeelInfo(MTHackLafProvider.java:61)
	at com.intellij.ide.ui.laf.LafManagerImpl.lambda$computeLafList$4(LafManagerImpl.java:194)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.ide.ui.laf.LafManagerImpl.computeLafList(LafManagerImpl.java:193)
	at com.intellij.ide.ui.laf.LafManagerImpl.lambda$new$0(LafManagerImpl.java:105)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:37)
	at com.intellij.ide.ui.laf.LafManagerImpl.findLaf(LafManagerImpl.java:381)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadLafState(LafManagerImpl.java:364)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:345)
	at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:74)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:441)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:536)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:610)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.ide.ui.LafManager.getInstance(LafManager.java:17)
	at com.intellij.idea.ApplicationLoader$initApplication$block$3$2.run(ApplicationLoader.kt:156)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
Please update to 7.5.2
