### ISSUE TITLE
[Bug]: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake

### ISSUE THREAD

**Issue by gerryhjs** [mallowigi/material-theme-issues#194]
### Describe the bug

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1696)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:608)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:367)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:296)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:52)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests.searchPlugins(MarketplaceRequests.kt:294)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fetchPlugins(RecommendedPluginsManager.kt:144)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.getRecommendedPlugins(RecommendedPluginsManager.kt:120)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fillPluginGroups(RecommendedPluginsManager.kt:127)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.init(RecommendedPluginsManager.kt:165)
	at com.mallowigi.idea.config.plugins.MTRecommendedPluginsForm.lambda$addPluginsToPanel$2(MTRecommendedPluginsForm.java:221)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	... 33 more

### To Reproduce

N/A

### Expected behavior

N/A

### Material Theme Version

v7.5.4

### IDE

IntelliJ IDEA

**Comment by gerryhjs** [comment]
@mallowigi happened when open "suggest plugins"

**Comment by mallowigi** [comment]
Maybe it's a configuration issue on your end, related with ssh?

**Comment by gerryhjs** [comment]
@mallowigi  I run the plugin at localhost. And my network is okay that time.

**Comment by mallowigi** [comment]
The error means that there is an issue fetching plugins because of a SSL connection. Do you reproduce it constantly? And is it happening with the Plugins manager as well?

**Comment by gerryhjs** [comment]
@mallowigi I didn't check that time if plugin marketplace can visit. I will tell you next time if I meet same problem again.
