### ISSUE TITLE
[Bug]: after update jetbrains-idea to 2022.2 (Build #IU-222.3345.118) and material update to 7.7.1 , material plugin can not use

### ISSUE THREAD

**Issue by wheesys** [mallowigi/material-theme-issues#205]
### Describe the bug

after update jetbrains-idea to 2022.2 (Build #IU-222.3345.118) , material version at 7.7.0, when i start idea, it prompt Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
i wait some day, and update material version to 7.7.1, the same err

### To Reproduce

1. update idea to 2022.2 

### Expected behavior

wait for fix

### Material Theme Version

v7.7.1

### IDE

IntelliJ IDEA

### System Info

```shell
evn is 
idea - Runtime version: 11.0.16+8 amd64
          VM: OpenJDK 64-Bit Server VM by Oracle Corporation
os - Manjaro Linux x86_64
       kernel 5.19.0-2-MANJARO
material - 7.7.0 and 7.7.1
```

### Logs/Screenshots

```shell
Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.UnsupportedClassVersionError: com/mallowigi/idea/MTHackComponent has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
    at java.base/java.lang.ClassLoader.defineClass2(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1109)
    at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
    at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
    at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
    at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
    at com.intellij.util.lang.ClassPath.findClassWithoutCache(ClassPath.java:235)
    at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:202)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:403)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:239)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:211)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:449)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:370)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:55)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:251)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:148)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:142)
    at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by wheesys** [comment]
and i have try remove settings, restart idea
that didn't work

**Comment by mallowigi** [comment]
Someone else reported at a similar issue, I see that you are still on JDK 11.

Is there a reason for it, or did it come bundled with the IDE?

Please make sure you're using JDK 17

**Comment by wheesys** [comment]
> 

it works, thx
