### ISSUE TITLE
[Bug]: Plugin throws errors on PhpStorm 2022.2.1 Preview

### ISSUE THREAD

**Issue by romanstingler** [mallowigi/material-theme-issues#206]
### Describe the bug

when starting the IDE I get immediately 2 errors
```
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:65)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:339)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:88)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:305)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:247)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:270)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:107)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda-2(MTLafComponent.kt:130)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

`java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:65)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:339)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:88)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:305)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:247)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:270)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:107)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda-0(MTLafComponent.kt:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

### To Reproduce

Get PhpStorm 2022.2.1 Preview
and start IDE with Material plugin enabled

### Expected behavior

no error

### Material Theme Version

7.7.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.2.1 Preview
Build #PS-222.3739.28, built on August 4, 2022
Subscription is active until August 31, 2022.
Runtime version: 18.0.2+9 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 5.18.16-arch1-1.1
GC: ZGC Cycles, ZGC Pauses
Memory: 8192M
Cores: 12
Registry:
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    org.intellij.plugins.hcl (222.3345.108)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.properties (222.3345.108)
    com.chrisrm.idea.MaterialThemeUI (7.7.1)
    com.github.mturlo.intellij.theme.spacegray (1.5.0)
    ru.adelf.idea.dotenv (2022.2)

Current Desktop: GNOME
```

**Comment by mallowigi** [comment]
Is there a reason why you're running with JDK 18? The plugin is not supported with this

**Comment by romanstingler** [comment]
I will accept your answer and suppress the errors. 
I don't want to start a rage discussion why they can't ship an ordinary openjdk version. 
They say so many super nice fixes and so much better, and openjdk needs so long to merge their code.

The only thing I and hundreds of other people can prove is that it breaks visuals, and other things.

**Comment by mallowigi** [comment]
So sorry about that.


Besides if it complained about this kind of errors, most likely the plugin won't be able to work on jdk 18 anyway...
