### ISSUE TITLE
[Bug]: NullPointerException Rider 2022.2.3

### ISSUE THREAD

**Issue by DasDirt** [mallowigi/material-theme-issues#226]
### Describe the bug

When you open a Rider project, the message. 
"Internal IDE error occurred" appears

### To Reproduce

Open any C# project with Rider 

### Expected behavior

The exception should not be thrown

### Material Theme Version

7.10.1

### IDE

Rider

### System Info

```shell
JetBrains Rider 2022.2.3
Build #RD-222.4167.23, built on September 9, 2022
Subscription is active until February 23, 2023.
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.editor.tab.selection.animation=true
    light.edit.file.open.enabled=false
    search.everywhere.settings=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false

Non-Bundled Plugins:
    indent-rainbow.indent-rainbow (2.0.2)
    com.intellij.plugins.expui (0.4)
    com.intellij.copyright (222.3739.67)
    com.andrey4623.rainbowcsv (2.0.2)
    com.jetbrains.rider.android (222.4167.23)
    zielu.gittoolbox (212.9.9)
    mobi.hsz.idea.gitignore (4.4.2)
    com.microsoft.vso.idea (1.162.0)
    izhangzhihao.rainbow.brackets (6.26)
    com.clutcher.comments_highlighter (2.4.1)
    com.chrisrm.idea.MaterialThemeUI (7.10.1)
```

### Logs/Screenshots

```shell
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViewsFont_u24lambda_u2d16_u24lambda_u2d15" is null
	at com.mallowigi.idea.MTThemeManager.refreshProjectViewsFont(MTThemeManager.kt:562)
	at com.mallowigi.idea.MTThemeManager.applyCustomTreeFont(MTThemeManager.kt:553)
	at com.mallowigi.idea.MTThemeManager.applyFonts(MTThemeManager.kt:525)
	at com.mallowigi.idea.MTLafComponent.lookAndFeelChanged(MTLafComponent.kt:75)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:448)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy1/jdk.proxy1.$Proxy39.lookAndFeelChanged(Unknown Source)
	at com.intellij.ide.ui.laf.LafManagerImpl.notifyLookAndFeelChanged(LafManagerImpl.java:846)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:836)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:311)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:238)
	at com.mallowigi.idea.MTLafComponent.activateTheme(MTLafComponent.kt:214)
	at com.mallowigi.idea.MTLafComponent.onSettingsChanged(MTLafComponent.kt:183)
	at com.mallowigi.idea.MTLafComponent$initComponent$2.configChanged(MTLafComponent.kt:132)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy3/jdk.proxy3.$Proxy194.configChanged(Unknown Source)
	at com.mallowigi.idea.config.application.MTConfig.fireChanged(MTConfig.java:359)
	at com.mallowigi.idea.config.application.MTConfig.activateFreePlan(MTConfig.java:534)
	at com.mallowigi.idea.license.MTLicenseManager.switchToFreePlan$lambda-0(MTLicenseManager.kt:120)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
I can't release an hotfix at the moment, but i think this version should fix it:

[Material Theme UI-7.10.2.zip](https://github.com/mallowigi/material-theme-issues/files/9600594/Material.Theme.UI-7.10.2.zip)

**Comment by DasDirt** [comment]
> I can't release an hotfix at the moment, but i think this version should fix it:
> 
> [Material Theme UI-7.10.2.zip](https://github.com/mallowigi/material-theme-issues/files/9600594/Material.Theme.UI-7.10.2.zip)

This seems to fix the problem
