### ISSUE TITLE
[Bug]: MTOverrideAccentColorAction#update@popup@MainToolbar (com.mallowigi.idea.actions.MTOverrideAccentColorAction), actionId=MTOverrideAccent, text='Override Accent Color from Theme'

### ISSUE THREAD

**Issue by duola8789** [mallowigi/material-theme-issues#227]
### Describe the bug

click the icon, then something wrong occurred，and icons in the contextmenu disappered

![image](https://user-images.githubusercontent.com/17665968/191150129-9a607cb6-20ee-4560-ad92-1ab305afbcc7.png)

![image](https://user-images.githubusercontent.com/17665968/191150406-5ebb1f67-32bc-4abb-895c-a5f15a0551e3.png)

```
MTOverrideAccentColorAction#update@popup@MainToolbar (com.mallowigi.idea.actions.MTOverrideAccentColorAction), actionId=MTOverrideAccent, text='Override Accent Color from Theme'

java.lang.NullPointerException: icon must not be null
	at com.mallowigi.idea.actions.MTToggleAction.update(MTToggleAction.kt:84)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:150)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:660)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:211)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:293)
	at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:778)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:291)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:210)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroup$0(Utils.java:183)
	at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:808)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:182)
	at com.intellij.ui.popup.ActionStepBuilder.appendActionsFromGroup(ActionStepBuilder.java:96)
	at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:68)
	at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:125)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:253)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:209)
	at com.intellij.openapi.actionSystem.impl.ActionButton$3.<init>(ActionButton.java:204)
	at com.intellij.openapi.actionSystem.impl.ActionButton.createAndShowActionGroupPopup(ActionButton.java:204)
	at com.intellij.openapi.actionSystem.impl.ActionButton.showActionGroupPopup(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:185)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### To Reproduce

1. click the icon in toolbar 
2.  something wrong

![image](https://user-images.githubusercontent.com/17665968/191150129-9a607cb6-20ee-4560-ad92-1ab305afbcc7.png)

### Expected behavior

show icon normally

### Material Theme Version

7.10.1

### IDE

WebStorm

### System Info

```shell
WebStorm 2022.2.2
Build #WS-222.4167.31, built on September 14, 2022
Licensed to old chow
You have a perpetual fallback license for this version.
Subscription is active until August 31, 2024.
Runtime version: 17.0.4+7-b469.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    ide.editor.tab.selection.animation=true
    search.everywhere.settings=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ideanginx9 (0.1.9)
    com.mallowigi (73.0.0)
    com.chrisrm.idea.MaterialThemeUI (7.10.1)

macOS Monterey
```

### Logs/Screenshots

```shell
1
```

**Comment by mallowigi** [comment]
I can't reproduce... Can you uninstall the plugin and install again and tell me if it changes anyhthing?

**Comment by duola8789** [comment]
> I can't reproduce... Can you uninstall the plugin and install again and tell me if it changes anyhthing?

I uninstalled it the plugin and install again, the error still here.

it looks like some icons are not found, some items seem are not showd in the dropdown 

![image](https://user-images.githubusercontent.com/17665968/191252195-5645770f-2858-4d89-913d-4e63c2d5a052.png)

I remember a 『Toggle High Contrast』 item in the dropdown, just like the error message metioned:

MTHighContrastAction#update@popup@MainToolbar (com.mallowigi.idea.actions.MTHighContrastAction), actionId=MTHighContrastAction, text='Toggle High Contrast'

java.lang.NullPointerException: icon must not be null

**Comment by duola8789** [comment]
![image](https://user-images.githubusercontent.com/17665968/191253108-e0b02bd0-c1a8-47dd-9e63-5507b9fca55e.png)

theses icons and some options are not showed at main tool bar dropdown, maybe something worng here, i guess

**Comment by mallowigi** [comment]
Well I don't know what to tell you... I've tested on many instances and i don't have any way to reproduce your issue...

**Comment by mallowigi** [comment]
Maybe if you clear the cache ?

**Comment by duola8789** [comment]
> Maybe if you clear the cache ?

Accually I don't know how to clear the cache of webstorm.

I can reproduce this bug everytime that I click the icon on toolbar. However, it's not fatal, just a little annoying.

I would to find out which funciton leadind to this bug, if i have time 

thank you

**Comment by mallowigi** [comment]
Menu > File > Invalidate Caches
