### ISSUE TITLE
[Bug]: Tab bar not rendered. (java.lang.NullPointerException: getInstance().tabHighlightPosition must not be null)

### ISSUE THREAD

**Issue by nvandijk** [mallowigi/material-theme-issues#230]
### Describe the bug

Tab bar is not rendered anymore. See screenshot and exception log.

<img width="1229" alt="Screenshot 2022-09-21 at 13 58 22" src="https://user-images.githubusercontent.com/333899/191498648-eb0997ee-2da3-4590-9e1b-8a4ecda2aa70.png">

### To Reproduce

Opening a project. Got an exception from PyCharm that the tab bar can't be rendered. Other components of the IDE are also not rendered anymore. 

### Expected behavior

Project and IDE should load normally with all IDE components rendered. 

### Material Theme Version

7.10.1

### IDE

PyCharm

### System Info

```shell
PyCharm 2022.2.1 (Professional Edition)
Build #PY-222.3739.56, built on August 16, 2022
Licensed to ***
You have a perpetual fallback license for this version.
Subscription is active until August 8, 2023.
Runtime version: 17.0.3+7-b469.37 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    me.lensvol.blackconnect (0.5.0)
    org.intellij.plugins.hcl (222.3739.24)
    YAML/Ansible support (0.11.2)
    String Manipulation (9.5.1)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    org.tonybaloney.security.pycharm-security (1.26.0)
    com.chrisrm.idea.MaterialThemeUI (7.10.1)
    ru.adelf.idea.dotenv (2022.2)
```

### Logs/Screenshots

```shell
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.mallowigi.idea.tabs.MTTabsPainterPatcherComponent$TabPainterInterceptor.intercept(MTTabsPainterPatcherComponent.kt:240)
	at com.mallowigi.idea.tabs.MTTabsPainter$$EnhancerByCGLIB$$a2b642b3.paintUnderline(<generated>)
	at com.intellij.ui.tabs.impl.JBEditorTabsBorder.paintBorder(JBEditorTabsBorder.kt:117)
	at com.intellij.ui.tabs.impl.JBTabsImpl.drawBorder(JBTabsImpl.java:2375)
	at com.intellij.ui.tabs.impl.JBTabsImpl.paintComponent(JBTabsImpl.java:2282)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NullPointerException: getInstance().tabHighlightPosition must not be null
	at com.mallowigi.idea.config.MTConfigManager.getTabHighlightPosition(MTConfigManager.kt:71)
	at com.mallowigi.idea.tabs.highlights.MTTabsHighlightPainter.paintHighlight(MTTabsHighlightPainter.kt:46)
	at com.mallowigi.idea.tabs.MTTabsPainter.paintUnderline(MTTabsPainter.kt:128)
	... 64 more
```

**Comment by nvandijk** [comment]
> Hi, I was trying to reproduce this bug. Can you send me your config file? Thanks

Here is an export of my settings (Manage IDE Settings -> Export Settings...). Is that what you need? 

[settings.zip](https://github.com/mallowigi/material-theme-issues/files/9623204/settings.zip)

**Comment by mallowigi** [comment]
Almost. What you gave me doesn't include the Material Theme settings so it doesn't help.

**Comment by nvandijk** [comment]
Okay, I looked around and found these two files. I also see that the `tabHighlightPosition` element has no value. Exception is related to this? 

```xml
# material_theme.xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="customTreeIndentEnabled" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isActiveBoldTab" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="statusBarTheme" value="false" />
    <option name="upperCaseButtons" value="false" />
    <option name="useMaterialWallpapers" value="true" />
    <option name="useProjectFrame" value="true" />
    <option name="customSidebarHeight" value="26" />
    <option name="rightTreeIndent" value="6" />
    <option name="settingsSelectedTab" value="4" />
    <option name="accentColor" value="f9826c" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="GITHUB_DARK" />
    <option name="userId" value="-41dbbe8e:1648f3f56e5:-8000" />
    <option name="version" value="7.8.1" />
    <option name="tabHighlightPosition" />
  </component>
</application>
```

```xml
# material_custom_theme.xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by nvandijk** [comment]
I think I've fixed my issue. I've set a correct value for the `tabHighlightPosition` setting. No clue why this was set to `None`...

**Comment by mallowigi** [comment]
I see, that feedback is helpful. Indeed, it is weird to why your value is null, but it shouldn't cause such an issue. I think the migration to Kotlin forced the value to be not-null, whereas it was loosely enforced before. I've added a fallback to circumvent this issue, I hope this is the only case.
