### ISSUE TITLE
[Bug]: java.net.UnknownHostException: plugins.jetbrains.com

### ISSUE THREAD

**Issue by simonschaufi** [mallowigi/material-theme-issues#245]
### Describe the bug

java.net.UnknownHostException: plugins.jetbrains.com thrown when I'm offline and starting PhpStorm.

```
java.net.UnknownHostException: plugins.jetbrains.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:608)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:367)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:298)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:52)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests.searchPlugins(MarketplaceRequests.kt:296)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fetchPlugins(RecommendedPluginsManager.kt:144)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fillPluginGroups(RecommendedPluginsManager.kt:122)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.init(RecommendedPluginsManager.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.net.UnknownHostException: plugins.jetbrains.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:608)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:359)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:367)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:298)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests$searchPlugins$marketplaceSearchPluginData$1.process(MarketplaceRequests.kt:52)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at com.intellij.ide.plugins.marketplace.MarketplaceRequests.searchPlugins(MarketplaceRequests.kt:296)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fetchPlugins(RecommendedPluginsManager.kt:144)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.fillPluginGroups(RecommendedPluginsManager.kt:122)
	at com.mallowigi.idea.config.plugins.RecommendedPluginsManager.init(RecommendedPluginsManager.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. go offline
2. open phpstorm
3. open a project
4. :boom: 

### Expected behavior

no error

### Material Theme Version

7.8.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.2.1
Build #PS-222.3739.61, built on August 18, 2022
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-126-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2986M
Cores: 8
Registry:
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.chrisrm.idea.MaterialThemeUI (7.8.1)
```

**Comment by mallowigi** [comment]
Hi,

While the plugin can work fine offline, some functions such as the "Recommended Plugins" require an online connection.

**Comment by simonschaufi** [comment]
Yes, but couldn't you catch this exception and do a different error handling?
