### ISSUE TITLE
[Bug]: Intellij IDEA Exception when launching the IDE

### ISSUE THREAD

**Issue by quonn77** [mallowigi/material-theme-issues#250]
### Describe the bug

When starting intellij (2022.2.2) with the material theme enabled I got an error which stack trace is reported below. Apart from the reported error the software seems to work.

### To Reproduce

Just launche Intellij with the Material Theme enabled. I am running it on an Ubuntu 16.04 environment

### Expected behavior

No exception should be raised

### Material Theme Version

v7.12.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.2.2 (Community Edition)
Build #IC-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-142-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 16
Registry:
    editor.focus.mode.color.light=474747
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=474747

Non-Bundled Plugins:
    idea.plugin.protoeditor (222.4167.21)
    com.jetbrains.plugins.ini4idea (222.4167.35)
    org.jetbrains.plugins.spotbugs (1.2.5)
    org.jetbrains.plugins.hocon (2022.1.0)
    eu.nyerel.panda.ij-plugin (1.1)
    com.aegamesi.java_visualizer.plugin (2.2.1)
    com.intellij.jira (4.2.0)
    VisualVMLauncher (1.21.211.6085.0)
    PlantUML integration (5.17.1)
    JFormDesigner (7.0.7.1)
    GrepConsole (12.15.211.6693.1)
    org.sonarlint.idea (7.1.1.54565)
    org.b333vv.metricstree (2020.1.12)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    PythonCore (222.4167.37)
    net.ashald.envfile (3.4.1)
    io.github.donkirkby.livepycharm (4.8.0)
    CheckStyle-IDEA (5.71.0)
    CMD Support (1.0.5)
    com.chrisrm.idea.MaterialThemeUI (7.12.0)
    SequenceDiagram (2.2.3)
    com.haulmont.jpab (2022.4.2-222)
    MavenRunHelper (4.21.222.2964.0)
    MetricsReloaded (1.12)
    com.kukido.eclipser (0.9.2)

Kotlin: 222-1.7.10-release-334-IJ4167.29
Current Desktop: X-Cinnamon
```

### Logs/Screenshots

```shell
ava.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:67)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:340)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:89)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:268)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:104)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda-2(MTLafComponent.kt:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:95)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
Please revert to 7.11.0.

Can you tell me when did you update to 7.12.0 ?

**Comment by quonn77** [comment]
I don't remember it was Intellij that proposed me to update the plugin.

Il gio 6 ott 2022, 11:05 Elior Boukhobza ***@***.***> ha
scritto:

**Comment by mallowigi** [comment]
This version is broken, I have removed it from the marketplace, that's why i find it odd that you got prompted to update.
