### ISSUE TITLE
[Bug]: IDE Internal Errors on Launch

### ISSUE THREAD

**Issue by JustinErdmier** [mallowigi/material-theme-issues#266]
### Describe the bug

Whenever I launch my IDE, it reports an internal error of an exception in Material Theme UI (7.14.2). 

### To Reproduce

Not sure... It's just happening when I launch my IDE; it doesn't appear to be changing the behavior.

### Expected behavior

I expect not to get an error every time I launch my IDE.

### Material Theme Version

v7.14.2

### IDE

Rider

### System Info

```shell
JetBrains Rider 022.2.3

Build #RD-222.4167.23, built on September 9, 2022

Licensed to Justin Erdmier
Subscription is active until November 27, 2022.

Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET 6.0.6
```

### Logs/Screenshots

```shell
stacktrace.txt
--------------
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViews_u24lambda_u241_u24lambda_u240" is null
	at com.mallowigi.idea.utils.MTUtils.refreshProjectViews(MTUtils.kt:108)
	at com.mallowigi.idea.utils.MTUiUtils.installMaterialTree(MTUiUtils.java:953)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:264)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:287)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:100)
	at com.mallowigi.idea.MTLafComponent.lookAndFeelChanged$lambda$1(MTLafComponent.kt:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.mallowigi.idea.MTLafComponent.lookAndFeelChanged(MTLafComponent.kt:76)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:448)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy2/jdk.proxy2.$Proxy37.lookAndFeelChanged(Unknown Source)
	at com.intellij.ide.ui.laf.LafManagerImpl.notifyLookAndFeelChanged(LafManagerImpl.java:846)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:836)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.handleCurrentSchemeSwitched(EditorColorsManagerImpl.java:186)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.lambda$onCurrentSchemeSwitched$0(EditorColorsManagerImpl.java:180)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
Can you remove and reinstall the plugin and tell me if it happens again?

**Comment by rog1039** [comment]
I get the exact same error and stack trace. Functionality seems to be unaffected. I did remove and reinstall plugin as suggested but that had no effect.

V17.4.2

JetBrains Rider 2022.2.4
Build #RD-222.4459.9, built on November 4, 2022
Runtime version: 17.0.5+7-b469.67 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 6.0.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 32
Registry:
    editor.focus.mode.color.light=515772
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=515772
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false

Non-Bundled Plugins:
    lermitage.intellij.extratci (1.23.0.201)
    com.intellij.rider.plugins.nuke (2022.2.0)
    com.intellij.resharper.StructuredLogging (2022.2.3.274)
    com.chylex.intellij.inspectionlens (1.1.0)
    String Manipulation (9.6.1)
    IdeaVIM (1.11.1)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-222)
    com.chrisrm.idea.MaterialThemeUI (7.14.2)

**Comment by konarx** [comment]
I also face the same error.

**Comment by mallowigi** [comment]
I can't reproduce this on 2022.3. Since the release is around the corner, please upgrade the IDE and check if the issue reproduces there. Thanks

**Comment by CraftingDragon007** [comment]
I get the same error:
```error
java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViews_u24lambda_u241_u24lambda_u240" is null
	at com.mallowigi.idea.utils.MTUtils.refreshProjectViews(MTUtils.kt:108)
	at com.mallowigi.idea.utils.MTUiUtils.installMaterialTree(MTUiUtils.java:953)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:251)
	at com.mallowigi.idea.MTLafComponent.activateTheme(MTLafComponent.kt:213)
	at com.mallowigi.idea.MTLafComponent.onSettingsChanged(MTLafComponent.kt:181)
	at com.mallowigi.idea.MTLafComponent$initComponent$2.configChanged(MTLafComponent.kt:130)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy4/jdk.proxy4.$Proxy181.configChanged(Unknown Source)
	at com.mallowigi.idea.config.application.MTConfig.fireChanged(MTConfig.java:371)
	at com.mallowigi.idea.config.application.MTConfig.activateFreePlan(MTConfig.java:554)
	at com.mallowigi.idea.license.MTLicenseManager.switchToFreePlan$lambda$0(MTLicenseManager.kt:120)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
System info:
```
JetBrains Rider 2022.2.4
Build #RD-222.4459.9, built on November 4, 2022
Runtime version: 17.0.5+7-b469.67 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
.NET 7.0
Material Theme UI Version: 7.14.2

**Comment by Kha-Lik** [comment]
Faced the same issue yesterday on Rider EAP 9
#279

**Comment by mallowigi** [comment]
Reproduced. I'll take a look in the weekend. In the meantime try to stay on previous EAP

**Comment by Kha-Lik** [comment]
Thank you, already rolled back to EAP 8

**Comment by mallowigi** [comment]
fixed. Please update. If you can't proceed to the plugins settings, please delete the plugin manually then reinstall.

**Comment by konarx** [comment]
> fixed. Please update. If you can't proceed to the plugins settings, please delete the plugin manually then reinstall.

@mallowigi can you please make it available for the release pipeline too? I am currently in 2002.2.4, not following EAPs
![image](https://user-images.githubusercontent.com/23631145/205869341-6b0fa48e-e718-4f1a-8ae0-01058185464f.png)

**Comment by mallowigi** [comment]
2022.3 released globally. I invite you to update.
