### ISSUE TITLE
[Bug]: org.jetbrains.mvstore.MVStoreException: File corrupted in chunk 3295

### ISSUE THREAD

**Issue by DonikaV** [mallowigi/material-theme-issues#268]
### Describe the bug

All the time erorrs in IDE

### To Reproduce

Open RubyMine

### Expected behavior

No errors

### Material Theme Version

73.0.0

### IDE

RubyMine

### System Info

```shell
RubyMine 2022.2.3
Build #RM-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    fr.gabrielcolson.prisma.prisma-intellij-plugin (1.2.5)
    com.mallowigi (73.0.0)
    intellij.prettierJS (222.4345.14)
    NodeJS (222.4345.14)
    net.ashald.envfile (3.4.1)
    com.chrisrm.idea.MaterialThemeUI (7.14.2)
    ru.adelf.idea.dotenv (2022.2)
    AngularJS (222.4345.14)
```

### Logs/Screenshots

```shell
org.jetbrains.mvstore.MVStoreException: File corrupted in chunk 3295, expected page length 4..63169, got -17571202
	at org.jetbrains.mvstore.Page.<init>(Page.java:121)
	at org.jetbrains.mvstore.LeafPage.<init>(LeafPage.java:26)
	at org.jetbrains.mvstore.MVStore.doReadPage(MVStore.java:2641)
	at org.jetbrains.mvstore.MVStore.lambda$readPage$9(MVStore.java:2625)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.jetbrains.mvstore.MVStore.readPage(MVStore.java:2625)
	at org.jetbrains.mvstore.NonLeafPage.getChildPage(NonLeafPage.java:62)
	at org.jetbrains.mvstore.Page.get(Page.java:205)
	at org.jetbrains.mvstore.MVMap.get(MVMap.java:372)
	at com.intellij.ui.svg.SvgCacheManager.loadFromCache(SvgCacheManager.kt:105)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.kt:117)
	at com.intellij.util.ImageLoader.loadByDescriptorWithoutCache(ImageLoader.java:264)
	at com.intellij.util.ImageLoader.loadByDescriptor(ImageLoader.java:223)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.java:154)
	at com.intellij.openapi.util.ImageDataByUrlLoader.loadImage(ImageDataByUrlLoader.java:89)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:979)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1048)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:866)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconHeight(IconLoader.java:799)
	at icons.AtomIcons.loadIconWithFallback(AtomIcons.kt:120)
	at com.mallowigi.icons.providers.DefaultFileIconProvider.getIcon(DefaultFileIconProvider.kt:50)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.loadIcon(AbstractFileIconProvider.kt:85)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation$lambda-0(AbstractFileIconProvider.kt:77)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIconForAssociation(AbstractFileIconProvider.kt:77)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.findIcon(AbstractFileIconProvider.kt:69)
	at com.mallowigi.icons.providers.AbstractFileIconProvider.getIcon(AbstractFileIconProvider.kt:52)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.psi.impl.ElementBase.doComputeIconNow(ElementBase.java:88)
	at com.intellij.psi.impl.ElementBase.lambda$computeIconNow$3(ElementBase.java:84)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.psi.impl.ElementBase.computeIconNow(ElementBase.java:84)
	at com.intellij.psi.impl.ElementBase.lambda$static$0(ElementBase.java:44)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:250)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$1(DeferredIconImpl.java:174)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:99)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$2(DeferredIconImpl.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:96)
	at com.intellij.ui.DeferredIconImpl.lambda$scheduleEvaluation$5(DeferredIconImpl.java:173)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:203)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mallowigi** [comment]
Wrong repositor, though I know about this issue, unfortunately I have no idea how to fix. Since this is not impacting usage, I'm closing this.
