### ISSUE TITLE
[Bug]: Rider crashes after upgrading to EAP 9

### ISSUE THREAD

**Issue by Kha-Lik** [mallowigi/material-theme-issues#279]
### Describe the bug

After upgrading to EAP 9 started to get startup exceptions when opening any project.

A new, empty 'ConsoleApp' project was opened successfully the first time, but on re-open got the same issue.
Also, after the PC reboot, I was able to open one of my projects, but again, only one of them, and once.

Disabling the Material Theme UI plugin removed the issue.

### To Reproduce

1. Upgrade Rider from EAP 8 to EAP 9
2. Try to open any existing project

### Expected behavior

The project is opened successfully

### Material Theme Version

v8.3.1

### IDE

Rider

### System Info

```shell
OS:
Windows 10 x64 21H2, build 19044.2251

Rider info:
Build #RD-223.7571.128, built on November 24, 2022

Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

.NET 7.0.0 (Server GC)

Plugin info:
Material Theme UI v8.3.1

Can't provide a config file for now.
```

### Logs/Screenshots

```shell
Full stack trace: 

Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.RuntimeException: Cannot invoke (class=MTLafComponent, method=appStarted, topic=AppLifecycleListener)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:639)
    at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:395)
    at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:374)
    at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
    at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:433)
    at jdk.proxy2/jdk.proxy2.$Proxy45.appStarted(Unknown Source)
    at com.intellij.idea.IdeStarter$start$2.invokeSuspend(IdeStarter.kt:77)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViews_u24lambda_u241_u24lambda_u240" is null
    at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:421)
    at com.mallowigi.idea.MTLafComponent.appStarted(MTLafComponent.kt:56)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:652)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
    ... 12 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.ide.projectView.impl.AbstractProjectViewPane.getTree()" because "$this$refreshProjectViews_u24lambda_u241_u24lambda_u240" is null
    at com.mallowigi.idea.utils.MTUtils.refreshProjectViews(MTUtils.kt:108)
    at com.mallowigi.idea.utils.MTUiUtils.installMaterialTree(MTUiUtils.java:953)
    at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:325)
    at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:264)
    at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:287)
    at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:100)
    at com.mallowigi.idea.MTLafComponent.appStarted$lambda$0(MTLafComponent.kt:58)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
    at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:97)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
    at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

-----
Your JRE: 17.0.5+1-b653.14 amd64 (JetBrains s.r.o.)
C:\Users\KoliaV\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\223.7571.128\jbr
```

**Comment by Kha-Lik** [comment]
Sorry, found a duplicate
