### ISSUE TITLE
[Bug]: crash when trying to add a new package.json from npm panel

### ISSUE THREAD

**Issue by zhigang1992** [mallowigi/material-theme-issues#280]
### Describe the bug

When pressing alt+F11 to bring up npm panel and click add file. it will crash
<img width="250" alt="image" src="https://user-images.githubusercontent.com/1057756/205305593-00648be6-0a32-4501-b0b8-811d3f6b8983.png">

<img width="1777" alt="image" src="https://user-images.githubusercontent.com/1057756/205305068-99b0ba10-3d82-4298-b35a-9cc0d79f3aea.png">

### To Reproduce

* Press alt+F11 
* Wait for the npm panel to show up
* Click on the plug button

### Expected behavior

It should be able to add `package.json`

### Material Theme Version

v8.3.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2022.3
Build #WS-223.7571.168, built on November 28, 2022
Licensed to Kyle Fang
Subscription is active until December 23, 2022.
Runtime version: 17.0.5+1-b653.14 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    co.anbora.labs.firebase-syntax-highlighting (2022.5.3)
    me.serce.solidity (2.3.10)
    AceJump (3.8.8)
    com.wakatime.intellij.plugin (14.1.2)
    IdeaVIM (2.0.0)
    com.mallowigi (80.0.0)
    mobi.hsz.idea.gitignore (4.4.4)
    com.intellij.database (223.7571.168)
    com.chrisrm.idea.MaterialThemeUI (8.3.1)
    com.intellij.lang.jsgraphql (3.3.0)
```

### Logs/Screenshots

```shell
java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.ui.popup.list.PopupInlineActionsSupport.hasExtraButtons, parameter element
	at com.intellij.ui.popup.list.PopupInlineActionsSupport.hasExtraButtons(PopupInlineActionsSupport.kt)
	at com.intellij.ui.popup.list.PopupListElementRenderer.updateExtraButtons(PopupListElementRenderer.java:397)
	at com.intellij.ui.popup.list.PopupListElementRenderer.customizeComponent(PopupListElementRenderer.java:277)
	at com.intellij.ui.popup.list.GroupedItemsListRenderer.getListCellRendererComponent(GroupedItemsListRenderer.java:57)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:312)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:653)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1728)
	at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:182)
	at com.intellij.ui.components.JBViewport.getPreferredSizeWithoutScrollBars(JBViewport.java:526)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:545)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:518)
	at com.intellij.ui.components.JBViewport$1.preferredLayoutSize(JBViewport.java:64)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1730)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:823)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1730)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1730)
	at com.intellij.ui.popup.WizardPopup$MyContainer.getPreferredSize(WizardPopup.java:325)
	at com.intellij.ui.popup.WizardPopup.show(WizardPopup.java:190)
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:557)
	at com.intellij.lang.javascript.buildTools.base.actions.JsbtAddBuildfileAction.lambda$actionPerformed$1(JsbtAddBuildfileAction.java:83)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by zhigang1992** [comment]
This bug happens when the material is disabled too. 🤦

**Comment by garethellis36** [comment]
I just updated to 2022.3 and I'm seeing this same error.

```
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to ICON Clinical Research / Gareth Ellis
Subscription is active until April 18, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry:
    editor.focus.mode.color.light=9ba0a3
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=9ba0a3

Non-Bundled Plugins:
    com.intellij.lang.puppet (223.7571.203)
    org.jetbrains.plugins.ruby (223.7571.123)
    com.jetbrains.php (223.7571.182)
    izhangzhihao.rainbow.brackets (2022.3.5)
    org.jetbrains.plugins.phpstorm-remote-interpreter (223.7571.117)
    org.exbin.deltahex.intellij (0.2.6)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    com.chrisrm.idea.MaterialThemeUI (8.3.1)
    com.intellij.php.psalm (223.7571.182)
    com.iconplc.itrans.plugin (2.4)
    com.jetbrains.php.rector (223.7571.182)
    com.vexus2.cakestorm (0.6.1)
    de.espend.idea.php.phpunit (6.2)

Kotlin: 223-1.7.20-release-201-IJ7571.182
```

The stack trace is the same as the one above. The dialog with the error specifically says it's an exception in this plugin.
