### ISSUE TITLE
[Bug]: PHPStorm become broken with "Unable to save settings"

### ISSUE THREAD

**Issue by pentatonicfunk** [mallowigi/material-theme-issues#304]
### Describe the bug

PhpStorm keep throwing error "Unable to save settings", and it says it related to Material Theme

### To Reproduce

1. Open PHPStorm
2. Edit Files
3. Error shown

"Unable to save settings"
Failed to save settings. Please restart PhpStorm

this also seems breaking phpcs checks in the PhpStorm

### Expected behavior

not breaking

### Material Theme Version

8.4.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2022.3.2
Build #PS-223.8617.59, built on January 30, 2023
Licensed to Hendrawan Kuncoro
Subscription is active until July 22, 2023.
Runtime version: 17.0.5+1-b653.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.chylex.intellij.inspectionlens (1.1.1)
    org.rust.lang (0.4.187.5175-223)
    org.toml.lang (223.8214.6)
    org.jetbrains.settingsRepository (223.8214.6)
    org.intellij.plugins.postcss (223.7571.117)
    com.atlassian.bitbucket.references (2022.1.220)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.mallowigi (85.1.0)
    mobi.hsz.idea.gitignore (4.4.4)
```

### Logs/Screenshots
https://imgur.com/a/nb2ABRQ

```shell
stacktrace log


Details: invalid.tagatt color span ?

java.lang.Throwable: Cannot parse HTML
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter$1.handleError(HtmlToSimpleColoredComponentConverter.java:101)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.handleError(DocumentParser.java:284)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:427)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:438)
	at java.desktop/javax.swing.text.html.parser.Parser.parseAttributeSpecificationList(Parser.java:1542)
	at java.desktop/javax.swing.text.html.parser.Parser.parseTag(Parser.java:1970)
	at java.desktop/javax.swing.text.html.parser.Parser.parseContent(Parser.java:2195)
	at java.desktop/javax.swing.text.html.parser.Parser.parse(Parser.java:2372)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135)
	at java.desktop/javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:114)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.convert(HtmlToSimpleColoredComponentConverter.java:107)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.appendHtml(HtmlToSimpleColoredComponentConverter.java:125)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.appendWithColoredMatches(GotoActionModel.java:957)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:824)
	at com.intellij.ide.actions.searcheverywhere.SEResultsListFactory.getNonMoreElementRenderer(SEResultsListFactory.java:90)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:72)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:312)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:561)
	at java.desktop/javax.swing.JList.setSelectedIndices(JList.java:2257)
	at com.intellij.ide.actions.searcheverywhere.SEListSelectionTracker.restoreSelection(SEListSelectionTracker.java:74)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$MySearchListener.elementsAdded(SearchEverywhereUI.java:1223)
	at com.intellij.ide.actions.searcheverywhere.SearchListener$1.elementsAdded(SearchListener.java:30)
	at com.intellij.ide.actions.searcheverywhere.BufferingListenerWrapper$Buffer.flush(BufferingListenerWrapper.java:94)
	at com.intellij.ide.actions.searcheverywhere.BufferingListenerWrapper.flushBuffer(BufferingListenerWrapper.java:28)
	at com.intellij.ide.actions.searcheverywhere.WaitForContributorsListenerWrapper.markContributorAndCheckFlush(WaitForContributorsListenerWrapper.java:93)
	at com.intellij.ide.actions.searcheverywhere.WaitForContributorsListenerWrapper.contributorWaits(WaitForContributorsListenerWrapper.java:84)
	at com.intellij.ide.actions.searcheverywhere.SwitchSEListener.contributorWaits(SwitchSEListener.java:46)
	at com.intellij.ide.actions.searcheverywhere.SearchListener$1.contributorWaits(SearchListener.java:40)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$addElement$4(MixedResultsSearcher.java:309)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$12(MixedResultsSearcher.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

induced logs
```
Following exceptions happened soon after this one, most probably they are induced.


2023-02-06T21:37:33.514

Details: invalid.tagatt color span ?
java.lang.Throwable: Cannot parse HTML
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter$1.handleError(HtmlToSimpleColoredComponentConverter.java:101)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.handleError(DocumentParser.java:284)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:427)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:438)
	at java.desktop/javax.swing.text.html.parser.Parser.parseAttributeSpecificationList(Parser.java:1542)
	at java.desktop/javax.swing.text.html.parser.Parser.parseTag(Parser.java:1970)
	at java.desktop/javax.swing.text.html.parser.Parser.parseContent(Parser.java:2195)
	at java.desktop/javax.swing.text.html.parser.Parser.parse(Parser.java:2372)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135)
	at java.desktop/javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:114)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.convert(HtmlToSimpleColoredComponentConverter.java:107)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.appendHtml(HtmlToSimpleColoredComponentConverter.java:125)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.appendWithColoredMatches(GotoActionModel.java:957)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:824)
	at com.intellij.ide.actions.searcheverywhere.SEResultsListFactory.getNonMoreElementRenderer(SEResultsListFactory.java:90)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:72)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:312)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:675)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2773)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:157)
	at com.intellij.ide.actions.searcheverywhere.MixedSearchListModel.addElements(MixedSearchListModel.java:52)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$MySearchListener.elementsAdded(SearchEverywhereUI.java:1220)
	at com.intellij.ide.actions.searcheverywhere.SearchListener$1.elementsAdded(SearchListener.java:30)
	at com.intellij.ide.actions.searcheverywhere.BufferingListenerWrapper$Buffer.flush(BufferingListenerWrapper.java:94)
	at com.intellij.ide.actions.searcheverywhere.BufferingListenerWrapper.flushBuffer(BufferingListenerWrapper.java:28)
	at com.intellij.ide.actions.searcheverywhere.WaitForContributorsListenerWrapper.markContributorAndCheckFlush(WaitForContributorsListenerWrapper.java:93)
	at com.intellij.ide.actions.searcheverywhere.WaitForContributorsListenerWrapper.contributorWaits(WaitForContributorsListenerWrapper.java:84)
	at com.intellij.ide.actions.searcheverywhere.SwitchSEListener.contributorWaits(SwitchSEListener.java:46)
	at com.intellij.ide.actions.searcheverywhere.SearchListener$1.contributorWaits(SearchListener.java:40)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$addElement$4(MixedResultsSearcher.java:309)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$12(MixedResultsSearcher.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)



2023-02-06T21:37:33.515

Details: invalid.tagatt color span ?
java.lang.Throwable: Cannot parse HTML
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter$1.handleError(HtmlToSimpleColoredComponentConverter.java:101)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.handleError(DocumentParser.java:284)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:427)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:438)
	at java.desktop/javax.swing.text.html.parser.Parser.parseAttributeSpecificationList(Parser.java:1542)
	at java.desktop/javax.swing.text.html.parser.Parser.parseTag(Parser.java:1970)
	at java.desktop/javax.swing.text.html.parser.Parser.parseContent(Parser.java:2195)
	at java.desktop/javax.swing.text.html.parser.Parser.parse(Parser.java:2372)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135)
	at java.desktop/javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:114)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.convert(HtmlToSimpleColoredComponentConverter.java:107)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.appendHtml(HtmlToSimpleColoredComponentConverter.java:125)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.appendWithColoredMatches(GotoActionModel.java:957)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:824)
	at com.intellij.ide.actions.searcheverywhere.SEResultsListFactory.getNonMoreElementRenderer(SEResultsListFactory.java:90)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:72)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.paintCell(MTListUI.kt:111)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at com.mallowigi.idea.ui.MTListUI.paint(MTListUI.kt:69)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:174)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at com.intellij.ui.components.JBList.paint(JBList.java:106)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:475)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)



2023-02-06T21:37:33.515

Details: invalid.tagatt color span ?
java.lang.Throwable: Cannot parse HTML
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter$1.handleError(HtmlToSimpleColoredComponentConverter.java:101)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.handleError(DocumentParser.java:284)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:427)
	at java.desktop/javax.swing.text.html.parser.Parser.error(Parser.java:438)
	at java.desktop/javax.swing.text.html.parser.Parser.parseAttributeSpecificationList(Parser.java:1542)
	at java.desktop/javax.swing.text.html.parser.Parser.parseTag(Parser.java:1970)
	at java.desktop/javax.swing.text.html.parser.Parser.parseContent(Parser.java:2195)
	at java.desktop/javax.swing.text.html.parser.Parser.parse(Parser.java:2372)
	at java.desktop/javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135)
	at java.desktop/javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:114)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.convert(HtmlToSimpleColoredComponentConverter.java:107)
	at com.intellij.ui.HtmlToSimpleColoredComponentConverter.appendHtml(HtmlToSimpleColoredComponentConverter.java:125)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.appendWithColoredMatches(GotoActionModel.java:957)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:824)
	at com.intellij.ide.actions.searcheverywhere.SEResultsListFactory.getNonMoreElementRenderer(SEResultsListFactory.java:90)
	at com.intellij.ide.actions.searcheverywhere.MixedListFactory$1.getListCellRendererComponent(MixedListFactory.java:72)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:275)
	at com.mallowigi.idea.ui.MTListUI.paintCell(MTListUI.kt:132)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at com.mallowigi.idea.ui.MTListUI.paint(MTListUI.kt:69)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:174)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at com.intellij.ui.components.JBList.paint(JBList.java:106)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:475)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Antiaris74** [comment]
Can confirm that this issue is reproducing on 8.4.1 plugin version, downgrade to 8.4.0 solves that problem

**Comment by mallowigi** [comment]
Can't reproduce. do you have a project i can test on?
