### ISSUE TITLE
[Bug]: `Go To Test` causes `NullPointerException`

### ISSUE THREAD

**Issue by Kevin-Lee** [mallowigi/material-theme-issues#311]
### Describe the bug

`Go To Test` causes `NullPointerException` with the error messages attached at the end of this issue ticket.
I have the same issue in both Scala and Java projects.

### To Reproduce

1. Clock on any `interface` or `class` in Java / `trait`, `class` or `object` in Scala that you want to create tests for
2. Hit `Shift + Cmd + T` (on macOS) or Right-click on it -> `Go To` -> `Test`
   <img width="861" alt="Screenshot 2023-02-26 at 3 08 04 pm" src="https://user-images.githubusercontent.com/2307335/221393682-cf271422-719e-49e8-9dbb-7c340b776461.png">
4. A notification popup with `IDE error occurred` containing the error messages attached at the end of this report appears.
   <img width="851" alt="Screenshot 2023-02-26 at 3 34 26 pm" src="https://user-images.githubusercontent.com/2307335/221392549-1a8d164b-052c-428e-b87d-bf168b4ea0b7.png">

### Expected behavior

A pop-up menu to choose a test file or create a new one just like [this one](https://www.jetbrains.com/help/idea/create-tests.html#test-code-navigation).

### Material Theme Version

v8.5.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.7665.28, built on February 23, 2023
Runtime version: 17.0.6+10-b829.1 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6b727d
    undo.documentUndoLimit=500
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.tooltip.initialDelay=507
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.nasller.CodeGlancePro (1.6.0-2023.1)
    org.jetbrains.settingsRepository (231.7665.20)
    com.andrey4623.rainbowcsv (2.0.2)
    indent-rainbow.indent-rainbow (2.1.0)
    com.wakatime.intellij.plugin (14.1.4)
    String Manipulation (9.6.1)
    GrepConsole (12.15.211.6693.1)
    org.intellij.scala (2023.1.475)
    izhangzhihao.rainbow.brackets (2023.2.5)
    com.chrisrm.idea.MaterialThemeUI (8.5.0)
    com.mallowigi (87.1.0)

Kotlin: 231-1.8.0-release-345-IJ7665.28
```

### Logs/Screenshots
<img width="1348" alt="Screenshot 2023-02-26 at 3 05 50 pm" src="https://user-images.githubusercontent.com/2307335/221391750-9266f038-f4e9-49d9-bc1f-ce99f163ada4.png">

```shell
java.lang.NullPointerException: Cannot invoke "com.intellij.navigation.TargetPresentation.getBackgroundColor()" because "presentation" is null
	at com.intellij.ui.list.TargetPresentationMainRenderer.customizeCellRenderer(TargetPresentationMainRenderer.kt:23)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:45)
	at com.intellij.ui.list.TargetPresentationRenderer.getListCellRendererComponent(TargetPresentationRenderer.kt:42)
	at com.intellij.codeInsight.navigation.GotoTargetRenderer.getListCellRendererComponent(GotoTargetRenderer.java:31)
	at com.intellij.openapi.ui.popup.util.RoundedCellRenderer.getListCellRendererComponent(RoundedCellRenderer.kt:21)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.updateLayoutState(MTListUI.kt:312)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at com.intellij.ui.popup.PopupListAdapter.autoSelect(PopupListAdapter.java:103)
	at com.intellij.openapi.ui.popup.PopupChooserBuilder.createPopup(PopupChooserBuilder.java:334)
	at com.intellij.codeInsight.navigation.GotoTargetHandler.show(GotoTargetHandler.java:189)
	at com.intellij.codeInsight.navigation.GotoTargetHandler.invoke(GotoTargetHandler.java:74)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$0(CodeInsightAction.java:68)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:155)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:598)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by Kevin-Lee** [comment]
I don't know what's changed, but it now works with the following IntelliJ IDEA version.
```
IntelliJ IDEA 2023.1 Beta (Ultimate Edition)
Build #IU-231.7864.76, built on March 2, 2023
```
I'm still using Material Theme UI `8.5.0`, so the cause of the problem I reported might not have anything to do with Material Theme UI.

Although I followed the suggestion from the error message and reported the bug here, sorry about reporting the wrong bug that may have nothing to do with Material Theme UI.

I'm closing the ticket.
