### ISSUE TITLE
[Bug]: Error on startup and when changing themes

### ISSUE THREAD

**Issue by chloecdn** [mallowigi/material-theme-issues#313]
### Describe the bug

There's an IDE-Error appearing everytime on startup, or when changing themes from the bottom-right of the IDE.
The IDE seems to still work perfectly fine, there's not a crash or anything like that, but errors are still bad ._.

### To Reproduce

1: Open IDE (Intellij IDEA Ultimate 2022.3.2), or change the active theme when already opened.
2: Error will appear

### Expected behavior

No Error

### Material Theme Version

v8.4.1

### IDE

IntelliJ IDEA

### System Info

```shell
Operating System: Arch Linux x86_64 - Kernel 6.2.1-arch1-1

IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Licensed to <my irl name>
Subscription is active until <subscription end date>.
Runtime version: 19.0.2+7 amd64
VM: OpenJDK 64-Bit Server VM by N/A
```

### Logs/Screenshots

```shell
https://i.imgur.com/NnNxEeO.png


java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:341)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:90)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:321)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:269)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:287)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:100)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$2(MTLafComponent.kt:122)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:97)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
```

**Comment by mallowigi** [comment]
You need to update to the latest version.

**Comment by mallowigi** [comment]
Also use JetBrains Toolbox because Arch Linux versions still use JDK 11 but the plugin only runs on JDK 17
