### ISSUE TITLE
[Bug]: IDE Internal Error - Exception in Material Theme (8.4.1)

### ISSUE THREAD

**Issue by marksweiss** [mallowigi/material-theme-issues#325]
### Describe the bug

Intellij reports an IDE error when opening a second or third project in a new window

<img width="824" alt="intellij_material_error" src="https://user-images.githubusercontent.com/58776/228958923-4904f2a5-7e6d-4f4f-a93c-fc1b425ae08c.png">

### To Reproduce

1. Open one project in Intellij
2. Open a different project in a new window

### Expected behavior

Second project should open without raising an error

### Material Theme Version

8.4.1

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.3.3 (Community Edition)
Build #IC-223.8836.41, built on March 9, 2023
Runtime version: 17.0.6+1-b653.34 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    debugger.watches.in.variables=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    ru.meanmail.plugin.requirements (2022.4.1)
    IdeaVIM (2.1.0)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-223)
    org.jetbrains.plugins.spotbugs (1.2.5)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.mallowigi (85.1.0)
    com.sourcegraph.jetbrains (2.1.2)

Kotlin: 223-1.8.0-release-345-IJ8836.41
```

### Logs/Screenshots

```shell
com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=Acervus, containerState=DISPOSE_COMPLETED, componentStore=/Volumes/code/Acervus) (disposed) (class com.intellij.openapi.project.impl.ProjectImpl) has already been disposed (see the cause for stacktrace) so the child: null 1577374230: running=false; canceled=false (class com.intellij.openapi.progress.util.ProgressWindow) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:95)
	at com.intellij.openapi.application.impl.ApplicationImpl.createProgressWindow(ApplicationImpl.java:695)
	at com.intellij.openapi.application.impl.ApplicationImpl.createProgressWindowAsyncIfNeeded(ApplicationImpl.java:680)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:387)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:524)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:284)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:238)
	at com.mallowigi.idea.MTStartupLicenseCheckActivity.runActivity$lambda$1(MTStartupLicenseCheckActivity.kt:40)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by AntonMenov** [comment]
I can't get the same error on my device _(Windows 10; IntelliJ IDEA 2023.1 (Ultimate Edition); v8.6.0)_.

Maybe you could update your IDE and plugin to the latest versions and that would fix this problem?
