### ISSUE TITLE
[Bug]: Material Theme ui v8.6.0 fails with newest version of intellij

### ISSUE THREAD

**Issue by greenhull** [mallowigi/material-theme-issues#352]
### Describe the bug

fails on startup info follows:

java.lang.NoSuchFieldError: myInfo2Label
	at com.mallowigi.idea.tabs.MTTabsPainterPatcherComponent.applyCustomFont(MTTabsPainterPatcherComponent.kt:158)
	at com.mallowigi.idea.tabs.MTTabsPainterPatcherComponent.patchPainter$lambda$3(MTTabsPainterPatcherComponent.kt:146)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:490)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:664)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$8(IdeEventQueue.kt:568)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1515)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:347)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:347)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:342)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:993)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:993)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$5(IdeEventQueue.kt:342)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:384)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

ABOUT info:

IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.6095.10, built on May 17, 2023
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: June 16, 2023
Runtime version: 17.0.7+7-b953.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1262M
Cores: 16
Registry:
    editor.focus.mode.color.light=e0861f
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=e0861f

Non-Bundled Plugins:
    com.chylex.intellij.inspectionlens (1.1.2)
    org.antlr.intellij.plugin (1.20)
    Gradle View (4.0.0)
    com.intellij.properties.bundle.editor (232.6095.10)
    org.sylfra.idea.plugins.linessorter (1.0.1)
    String Manipulation (9.7.1)
    com.github.platan.gradle-dependencies-formatter (0.6.1)
    tarn.gradle.dependencies (1.6.2)
    MavenRunHelper (4.23.222.2964.0)
    GrepConsole (12.18.211.6693.0)
    PlantUML integration (6.1.0-IJ2022.2)
    org.sonarlint.idea (8.2.0.68615)
    izhangzhihao.rainbow.brackets (2023.2.7)
    GradleDependenciesHelper (1.16)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    com.mallowigi (90.0.0)
    com.kn.diagrams.generator.generator (2022.2.0)

Kotlin: 232-1.8.21-release-380-IJ6095.10

### To Reproduce

1 install material theme on release: IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.6095.10, built on May 17, 2023
2 restart and get error

### Expected behavior

normal startup

### Material Theme Version

v8.6.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.6095.10, built on May 17, 2023
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: June 16, 2023
Runtime version: 17.0.7+7-b953.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1262M
Cores: 16
Registry:
    editor.focus.mode.color.light=e0861f
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=e0861f

Non-Bundled Plugins:
    com.chylex.intellij.inspectionlens (1.1.2)
    org.antlr.intellij.plugin (1.20)
    Gradle View (4.0.0)
    com.intellij.properties.bundle.editor (232.6095.10)
    org.sylfra.idea.plugins.linessorter (1.0.1)
    String Manipulation (9.7.1)
    com.github.platan.gradle-dependencies-formatter (0.6.1)
    tarn.gradle.dependencies (1.6.2)
    MavenRunHelper (4.23.222.2964.0)
    GrepConsole (12.18.211.6693.0)
    PlantUML integration (6.1.0-IJ2022.2)
    org.sonarlint.idea (8.2.0.68615)
    izhangzhihao.rainbow.brackets (2023.2.7)
    GradleDependenciesHelper (1.16)
    com.chrisrm.idea.MaterialThemeUI (8.6.4)
    com.mallowigi (90.0.0)
    com.kn.diagrams.generator.generator (2022.2.0)

Kotlin: 232-1.8.21-release-380-IJ6095.10
```

**Comment by greenhull** [comment]
Actual version of material theme ui is : 8.6.4 not 8.6.0

**Comment by mallowigi** [comment]
I'm aware of this issue. But because of the volatility of the eap ill wait a bit before releasing a hotfix. Does that prevent you from using the plugin?

**Comment by vegidio** [comment]
I'm having the same problem with version 8.7.1 and `IntelliJ IDEA 2023.1.3 (Ultimate Edition) Build #IU-231.9161.38, built on June 20, 2023`. The plugin is not usable anymore with this version of the IDE.

**Comment by bedge** [comment]
> I'm aware of this issue. But because of the volatility of the eap ill wait a bit before releasing a hotfix. Does that prevent you from using the plugin?

Still happening 3 months later.
Every time a new project is opened one has to dismiss the error.

**Comment by mallowigi** [comment]
It shouldn't happened. Can you provide a screenshot as well as your system specs?
