### ISSUE TITLE
[Bug]: Atom Material Icons for PHPStorm crashes IDE

### ISSUE THREAD

**Issue by vipex** [mallowigi/material-theme-issues#359]
### Describe the bug

When open a project, editor opens but remain stuck with interface unresponsive, in `idea.log` there are many SEVERE log entries.

### To Reproduce

Open PHPStorm then open any project. Disabling the plugin everything starts working again.

### Expected behavior

The IDE should work

### Material Theme Version

8.7.1

### IDE

PHPStorm

### System Info

```shell
PhpStorm 2023.1.2
Build #PS-231.9011.38, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=474747
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=474747

Non-Bundled Plugins:
    AWSCloudFormation (231.8109.91)
    com.github.copilot (1.2.8.2631)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.intellij.properties (231.8770.3)
    com.intellij.jira (4.4.2)
    com.kalessil.phpStorm.phpInspectionsEA (5.0.0.0)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.4.0)
    com.atlassian.bitbucket.references (2022.1.240)
    com.chrisrm.idea.MaterialThemeUI (8.7.1)
    zielu.gittoolbox (500.0.10+213)
    mobi.hsz.idea.gitignore (4.5.0)
    aws.toolkit (1.69-231)
```

### Logs/Screenshots

```shell
2023-06-16 12:38:38,524 [ 137903] SEVERE - #c.i.i.p.PluginManager - PhpStorm 2023.1.2  Build #PS-231.9011.38
2023-06-16 12:38:38,524 [ 137903] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-06-16 12:38:38,524 [ 137903] SEVERE - #c.i.i.p.PluginManager - OS: Mac OS X
2023-06-16 12:38:38,524 [ 137903] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: Atom Material Icons version: 91.0.0
2023-06-16 12:32:20,770 [ 205045] SEVERE - #c.i.i.p.PluginManager - Method com/mallowigi/icons/svgpatchers/MainSvgPatcher.forPath(Ljava/lang/String;)Lcom/intellij/util/SVGLoader$SvgElementColorPatcher; is abstract
java.lang.AbstractMethodError: Method com/mallowigi/icons/svgpatchers/MainSvgPatcher.forPath(Ljava/lang/String;)Lcom/intellij/util/SVGLoader$SvgElementColorPatcher; is abstract
	at com.mallowigi.icons.svgpatchers.MainSvgPatcher.forPath(MainSvgPatcher.kt)
	at com.intellij.util.ImageLoaderKt.loadByDescriptor(ImageLoader.kt:521)
	at com.intellij.util.ImageLoaderKt.access$loadByDescriptor(ImageLoader.kt:1)
	at com.intellij.util.ImageLoader.loadImage(ImageLoader.kt:86)
	at com.intellij.openapi.util.ImageDataByUrlLoader.loadImage(ImageDataByUrlLoader.java:87)
	at com.intellij.openapi.util.CachedImageIcon.loadImage$intellij_platform_util_ui(CachedImageIcon.kt:269)
	at com.intellij.openapi.util.ScaledIconCache.getOrScaleIcon(ScaledIconCache.kt:46)
	at com.intellij.openapi.util.CachedImageIcon.getRealIcon$intellij_platform_util_ui(CachedImageIcon.kt:151)
	at com.intellij.openapi.util.CachedImageIcon.getIconWidth(CachedImageIcon.kt:104)
	at com.intellij.openapi.wm.impl.status.TextPanel$WithIconAndArrows.getIconX(TextPanel.kt:203)
	at com.intellij.openapi.wm.impl.status.TextPanel$WithIconAndArrows.paintComponent(TextPanel.kt:176)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.paintChildren(IdeStatusBarImpl.kt:509)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:247)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1101)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3983)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.kt:89)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:893)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:380)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
Wrong repo
