### ISSUE TITLE
[Bug]: Material Theme UI 8.9.0 incompatible with WebStorm 2023.2

### ISSUE THREAD

**Issue by RobertTheDude** [mallowigi/material-theme-issues#371]
### Describe the bug

Material Theme UI 8.9.0 is not working in WebStorm 2023.2.  All menus, etc. are not displayed except the main "WebStorm" menu.  I'm a paid subscriber for more than a year.

This is the error message:
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultColor' of com/intellij/ui/JBColor.namedColor must not be null
	at com.intellij.ui.JBColor.$$$reportNull$$$0(JBColor.java)
	at com.intellij.ui.JBColor.namedColor(JBColor.java)
	at com.mallowigi.idea.utils.MTUI$Panel.getAccentColor(MTUI.kt:949)
	at com.mallowigi.idea.UIReplacer.patchColors(UIReplacer.kt:140)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:92)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:347)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:118)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda$1(MTLafComponent.kt:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:100)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### To Reproduce

Just try to launch WebStorm 2023.2 with Material Them UI plugin 8.9.0 enabled.

### Expected behavior

Should be able to launch WebStorm and have full functionality.

### Material Theme Version

8.9.0

### IDE

WebStorm

### System Info

```shell
WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Licensed to Robert Supples
Subscription is active until August 13, 2023.
Runtime version: 17.0.7+7-b1000.6 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=999999
    ide.editor.tab.selection.animation=true
    ide.animate.toolwindows=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=999999

Non-Bundled Plugins:
    com.vermouthx.xcode-theme (1.6.1)
    com.villains.intelij.plugin.trashpandatheme (1.6)
    com.jetbrains.space (232.8660.158)
    com.markskelton.one-dark-theme (5.8.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    com.chrisrm.idea.MaterialThemeUI (8.9.0)
    com.github.dinbtechit.vscodetheme (1.8.5)
    com.mallowigi (91.0.0)
```

**Comment by mallowigi** [comment]
what theme are you using to see this error?

**Comment by RobertTheDude** [comment]
Update: If I uninstall v8.9.0 of the Material Theme UI plugin, and install the prior version (v8.8.1) - there are no issues.

**Comment by mallowigi** [comment]
Thanks. I'll investigate

**Comment by mallowigi** [comment]
[Material Theme UI-8.9.1.zip](https://github.com/mallowigi/material-theme-issues/files/12162704/Material.Theme.UI-8.9.1.zip)

Please install this and tell me if it solves your pborblem

**Comment by dwyart** [comment]
Still broken for me on DataGrip 2023.2

**Comment by dwyart** [comment]
Solarized Dark from "Solarized Themes" plugin

**Comment by mallowigi** [comment]
I've checked all the solarized themes and I couldn't reproduce.

**Comment by RobertTheDude** [comment]
ANY theme.  

I’m Running on a MacBook Pro, M2 Max processor, on MacOS Ventura 13.5 (22G74).

**Comment by mallowigi** [comment]
no way. with the 8.9.1?

**Comment by RobertTheDude** [comment]
Good news.  Installing 8.9.1 resolved the issue.  Thank you for the quick response.

**Comment by RobertTheDude** [comment]
This issue can be closed as far as I'm concerned.  Shall I close it @mallowigi or is that something you do?
