### ISSUE TITLE
[Bug]: kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by marek-miotelka** [mallowigi/material-theme-issues#404]
### Describe the bug

Error started showing up after the last update to 8.12.0

kotlin.UninitializedPropertyAccessException: lateinit property DESCRIPTORS has not been initialized
	at com.mallowigi.idea.config.MTFileColorsPage.getColorDescriptors(MTFileColorsPage.kt:58)
	at com.intellij.application.options.colors.ColorAndFontOptions.initDescriptions(ColorAndFontOptions.java:586)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:542)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:531)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:515)
	at com.intellij.application.options.colors.ColorAndFontOptions.resetImpl(ColorAndFontOptions.java:656)
	at com.intellij.application.options.colors.ColorAndFontOptions.reset(ColorAndFontOptions.java:668)
	at com.mallowigi.idea.MTThemeManager.resetColorScheme(MTThemeManager.kt:872)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda$1(MTLafComponent.kt:77)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:100)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
<img width="822" alt="Screenshot 2023-09-26 at 19 06 28" src="https://github.com/mallowigi/material-theme-issues/assets/104889285/4bfc8dbe-1b2b-475a-8dbc-f48f1fef2eda">

### To Reproduce

1. Open IDE
2. Error pops up

### Expected behavior

No error. 

### Material Theme Version

v8.12.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Licensed to Marek Miotelka
Subscription is active until January 5, 2024.
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16000M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=6a737d
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.mac.stage.manager.support=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6a737d

Non-Bundled Plugins:
    com.intellij.apacheConfig (232.9921.55)
    com.intellij.plugins.watcher (232.8660.88)
    com.intellij.lang.liquid (232.8660.88)
    org.jetbrains.plugins.localization (232.8660.88)
    lermitage.intellij.extra.icons (2023.2.11-231)
    String Manipulation (9.11.3)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.intellij.prisma (232.9559.10)
    dev.nx.console (1.13.1)
    com.rxliuli.vite-jetbrains-plugin (0.2.2)
    com.dmarcotte.handlebars (232.8660.88)
    com.intellij.react.css.modules (1.0.1)
    com.jetbrains.lang.ejs (232.8660.142)
    com.atlassian.bitbucket.references (2022.1.242)
    Pythonid (232.9921.47)
    net.ashald.envfile (3.4.1)
    zielu.gittoolbox (500.0.20+222)
    mobi.hsz.idea.gitignore (4.5.1)
    com.jetbrains.php (232.9921.55)
    com.jetbrains.twig (232.9921.55)
    com.chrisrm.idea.MaterialThemeUI (8.12.0)
    com.jetbrains.php.wordPress (232.9921.55)

Kotlin: 232-1.9.0-IJ9921.47
```

**Comment by Adriansun** [comment]
Got the same. https://github.com/ChrisRM/material-theme-jetbrains/issues/1906

**Comment by JosephTico** [comment]
Same issue

**Comment by lzrf0cuz** [comment]
> 8.12.2 error still present

+1

**Comment by xiaobili** [comment]
+1

**Comment by davidabreu7** [comment]
same error here

**Comment by w5hh** [comment]
俺也一样

**Comment by mallowigi** [comment]
fixed
