### ISSUE TITLE
[Bug]: IDE crashing

### ISSUE THREAD

**Issue by Lucasmellof** [mallowigi/material-theme-issues#433]
### Describe the bug

IDE started crashing when I updated to the latest version (IDEA 2023.3.1 and RustRover 2023.3 EAP).
 

### To Reproduce

1. Update IDE
2. Update plugins to the latest version
3. Restart IDE
4. Crash

### Expected behavior

Not crash

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA, Other (AppCode, CLion, GoLang...)

### System Info

```shell
RustRover (build #RR-233.11799.284, Mon, 11 Dec 2023 19:15:00 GMT)
OS: Windows (11.0)
JRE: 17.0.9+7-b1087.7, amd64 (JetBrains s.r.o.)
JVM: 17.0.9+7-b1087.7 (OpenJDK 64-Bit Server VM)
```

### Logs/Screenshots

```shell
2023-12-13 00:47:01,871 [   1652] SEVERE - #c.i.i.p.PluginManager - null
java.lang.ExceptionInInitializerError
	at com.mallowigi.idea.themes.MTAccents.<clinit>(MTAccents.kt:52)
	at com.mallowigi.idea.config.application.MTConfig.<clinit>(MTConfig.java:119)
	at com.mallowigi.idea.MTThemeManager.<init>(MTThemeManager.kt:88)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:41)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:39)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:278)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:39)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:47)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$getOrCreateInstanceBlocking$3.invokeSuspend(ComponentManagerImpl.kt:2337)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2406)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2397)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:2397)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:2336)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1057)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:988)
	at com.mallowigi.idea.MTThemeManager$Companion$instance$2.invoke(MTThemeManager.kt:926)
	at com.mallowigi.idea.MTThemeManager$Companion$instance$2.invoke(MTThemeManager.kt:921)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.mallowigi.idea.MTThemeManager$Companion.getInstance(MTThemeManager.kt:921)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:120)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:443)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NullPointerException: getAccentColor(...) must not be null
	at com.mallowigi.idea.svgPatchers.MTThemeColorPatcher.getAccentColor(MTThemeColorPatcher.kt:42)
	at com.mallowigi.idea.svgPatchers.MTThemeColorPatcher.digest(MTThemeColorPatcher.kt:112)
	at com.intellij.ui.svg.SvgKt.colorPatcherDigestShim(svg.kt:86)
	at com.intellij.ui.icons.CustomColorPatcherStrategy.<init>(CachedImageIcon.kt:389)
	at com.intellij.ui.icons.CachedImageIcon.createWithPatcher(CachedImageIcon.kt:299)
	at com.intellij.ui.icons.CachedImageIcon.createWithPatcher$default(CachedImageIcon.kt:292)
	at com.intellij.ui.svg.SvgKt$patchIconsWithColorPatcher$1.invoke(svg.kt:352)
	at com.intellij.ui.svg.SvgKt$patchIconsWithColorPatcher$1.invoke(svg.kt:351)
	at com.intellij.ui.svg.SvgKt.replaceCachedImageIcons(svg.kt:361)
	at com.intellij.ui.svg.SvgKt.patchIconsWithColorPatcher(svg.kt:351)
	at com.intellij.ui.svg.SvgKt.access$patchIconsWithColorPatcher(svg.kt:1)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1$1.invoke(svg.kt:344)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1$1.invoke(svg.kt:343)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1.invoke$lambda$0(svg.kt:343)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58)
	at com.intellij.ui.svg.SvgKt.colorPatchedIcon(svg.kt:347)
	at com.mallowigi.idea.utils.IconExtensionsKt.themedIcon(IconExtensions.kt:35)
	at com.mallowigi.idea.utils.MTIcons.<clinit>(MTIcons.kt:41)
	... 79 more
```

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-issues/issues/426
