### ISSUE TITLE
[Bug]: RuntimeExceptionWithAttachments "Read access is allowed from inside read-action"

### ISSUE THREAD

**Issue by rherrick** [mallowigi/material-theme-issues#436]
### Describe the bug

Noticed the error light flashing in IntelliJ and found an error message for the plugin:

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[AWT-EventQueue-0,6,main] 482255043 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:182)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:612)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:947)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:33)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:344)
	at com.intellij.psi.impl.source.PsiClassImpl.getQualifiedName(PsiClassImpl.java:149)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$1.getTextFor(AddImportAction.java:143)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction$1.getTextFor(AddImportAction.java:108)
	at com.intellij.ui.popup.list.PopupListElementRenderer$1.getTextFor(PopupListElementRenderer.java:53)
	at com.intellij.ui.popup.list.GroupedItemsListRenderer.getListCellRendererComponent(GroupedItemsListRenderer.java:38)
	at com.intellij.codeInsight.daemon.impl.actions.AddImportAction.lambda$chooseClassAndImport$1(AddImportAction.java:155)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.paintCell(MTListUI.kt:111)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at com.mallowigi.idea.ui.MTListUI.paint(MTListUI.kt:69)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:189)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.components.JBList.paint(JBList.java:110)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:235)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:272)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1101)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3988)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:893)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:386)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### To Reproduce

I have no idea. I actually wasn't even using the IDE most of the time this afternoon, so I didn't see this until I switched back to it from another app.

### Expected behavior

Not getting an error message.

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 11, 2023
Licensed to XXXXXX
Subscription is active until XXXXX
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=828bb8
  editor.focus.mode.color.dark=828bb8
  debugger.new.tool.window.layout=true
  ide.rename.preview.dialog=true
  external.system.substitute.library.dependencies=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (233.11799.300)
  manjaro.mpb (1.8)
  com.nasller.CodeGlancePro (1.7.7)
  org.nik.presentation-assistant (1.0.10)
  com.github.copilot (1.4.5.4049)
  YourKit Java Profiler 2023.5-b224 Integration (2023.5.224.0)
  com.intellij.guice (233.11799.196)
  com.crunch42.openapi (1.69)
  com.intellij.bigdatatools.core (233.11799.300)
  com.intellij.bigdatatools.binary.files (233.11799.267)
  com.intellij.bigdatatools.rfs (233.11799.300)
  com.intellij.bigdatatools.metastore.core (233.11799.267)
  com.intellij.bigdatatools.flink (233.11799.267)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  JProfiler (19.9.3)
  com.haulmont.jpab (2023.4.1-233)
  com.mallowigi (94.1.0)
  com.intellij.bigdatatools.kafka (233.11799.267)
  com.microsoft.tooling.msservices.intellij.azure (3.83.0-2023.3)
  com.intellij.bigdatatools.spark (233.11799.267)
  com.intellij.bigdatatools.zeppelin (233.11799.267)
  com.intellij.bigdatatools (233.11799.267)
Kotlin: 233.11799.300-IJ
```

**Comment by AntonMeenov** [comment]
The same issue and the same error message using the latest version Windows 10.
The same version of IntelliJ and Material Theme UI.

One non-default plugin is "Atom Material Icons".

This happens when I click "Import static method..." and the "Method to Import" menu opens (pictures below).
Didn't test any further, but to be specific, it happens in my Gradle - Spring Boot - Java project.

If I clear the error message and repeat the same action, the error message does not appear until the IDE is restarted; after restart, it will appear again.

[1]
![image](https://github.com/mallowigi/material-theme-issues/assets/20296415/9efd09e5-0840-4650-9f9c-6cb985c22442)

[2]
![image](https://github.com/mallowigi/material-theme-issues/assets/20296415/d5249b9a-b984-4fc3-9861-e8eb92b34885)

**Comment by mCassy** [comment]
Same issue as above.
PHPStrom version: 2023.3
Material UI version: 8.13.2
Atom Material Icons plugin is installed.

**Comment by mallowigi** [comment]
duplicate, closing.
