### ISSUE TITLE
[Bug]: Errors when working with JBR 21

### ISSUE THREAD

**Issue by Soromeister** [mallowigi/material-theme-issues#450]
### Describe the bug

Getting the below exceptions on startup:

1st exception:
```
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:426)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:84)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:347)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:286)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:443)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

2nd exception:
```
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:426)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:84)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:347)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:286)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda$1(MTLafComponent.kt:79)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:101)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Everything that I use from the theme works as expected, but these exceptions are annoying.

### To Reproduce

1. Double-press SHIFT to pop-out the quick actions panel
2. Search for "Boot Java"
3. Select "Choose Boot Java runtime for the IDE...
4. Select a JBR 21 SDK (With JCEF) or download one and point to it
5. Restart IntelliJ IDEA
6. Exceptions occur

### Expected behavior

Exceptions shouldn't occur

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA

### System Info

```
shell
IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 25, 2024
Licensed to Myself
Subscription is active until August 21, 2024.
For educational use only.
Runtime version: 21.0.2+13-b341.4 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=474747
  editor.focus.mode.color.dark=474747
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  editor.minimap.enabled=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  Batch Scripts Support (1.0.13)
  lermitage.intellij.extratci (1.31.1)
  com.nasller.CodeGlancePro (1.7.8)
  com.intellij.plugins.macoskeymap (232.6095.10)
  com.jetbrains.naming-is-hard (1.5.0)
  com.mallowigi.imageicon (14.0.0)
  com.intellij.plugins.vscodekeymap (233.11799.188)
  color.scheme.Molokai (1.5)
  name.kropp.intellij.makefile (233.13135.65)
  com.intellij.plugins.watcher (233.13135.65)
  com.fabio (1.2)
  de.netnexus.camelcaseplugin (3.0.12)
  org.jetbrains.plugins.go-template (233.11799.172)
  lermitage.intellij.extra.icons (2024.2.2)
  dev.turingcomplete.intellij-gradle-utilities-plugin (1.2.5)
  com.intellij.nativeDebug (233.14015.106)
  com.jetbrains.jax.ws (233.13135.65)
  com.intellij.spring.shell (233.11799.196)
  com.intellij.spring.websocket (233.11799.196)
  CheckStyle-IDEA (5.85.1)
  com.intellij.spring.batch (233.14015.23)
  org.jspresso.plugin.i18n (1.2.4)
  org.jetbrains.jumpToLine (0.1.15)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.intellij.spring.webflow (233.11799.300)
  net.seesharpsoft.intellij.plugins.csv (3.2.3-233)
  com.github.copilot (1.4.13.4415)
  mobi.hsz.idea.gitignore (4.5.2)
  com.intellij.javaee.batch (233.11799.196)
  Jetty (233.11799.196)
  com.intellij.spring.ws (233.11799.196)
  org.mapstruct.intellij (1.6.1)
  dev.jbang.intellij.JBangPlugin (0.24.4)
  com.haulmont.jpab (2023.4.1-233)
  com.intellij.tide (233.13763.11)
  io.jetclient (2023.1.19-233)
  zielu.gittoolbox (500.1.8+222)
  com.intellij.plugins.html.instantEditing (233.13135.65)
  com.jetbrains.php (233.14015.106)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  com.mallowigi.colorHighlighter (18.0.0)
  de.espend.idea.php.annotation (9.4.0)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  com.github.lppedd.idea-return-highlighter (0.8.3)
  com.mallowigi (94.1.0)
Kotlin: 233.14015.106-IJ
```

Custom properties file:

```
# custom IntelliJ IDEA properties (expand/override 'bin/idea.properties')
editor.zero.latency.typing=true
```

Custom VM Options:
```
-Xms1g
-Xmx8g
-Xss64m
-XX:+UseG1GC
-XX:+AllowEnhancedClassRedefinition
-XX:+UseStringDeduplication
-Dfile.encoding=UTF-8
-Dhidpi=true
-Dsun.java2d.noddraw=false
-Dsun.java2d.d3d=true
-Dsun.java2d.ddforcedram=true
-Dsun.java2d.metal=true
-Dsun.java2d.opengl=true
-Djava.net.preferIPv4Stack=true
-XX:-OmitStackTraceInFastThrow
-XX:+UnlockExperimentalVMOptions
-Xverify:none
```

### Logs/Screenshots

<img width="686" alt="Screenshot 2024-01-29 at 10 49 17" src="https://github.com/mallowigi/material-theme-issues/assets/45243695/61fac122-c637-4784-8b95-b60db5adfbc5">

**Comment by mallowigi** [comment]
These exceptions happen when you're not on the JDK version 17. 

Are you using JetBrains Toolbox ?

**Comment by Soromeister** [comment]
Yes, I am using JetBrains Toolbox indeed.

**Comment by mallowigi** [comment]
I have seen that JB moved to JBR 21 as of recently. As a result a lot of plugin features are no longer working. 

I'm fixing them one by one at the moment, but it will take some time to complete. 

However normally this change is only for 2024.1+ so I don't understand how you are experiencing these issues on 2023

EDIT: I just saw that you changed the version explicitly, which means that 2023 users are normally not affected yet, that's good to know.

**Comment by Soromeister** [comment]
Yes, I am indeed using it explicitly. The theme is not really affected (at least not the parts that I'm using), it's just that this error is annoying as it the IDE starts with that. Feel free to close this issue if you want to, since you are aware.

**Comment by Voyinno** [comment]
Hello, have you been able to correct the error? I am currently facing the same problem in another project.

**Comment by mallowigi** [comment]
It should be working with the latest version (9.1.0)
