### ISSUE TITLE
material theme 8.23.3 on intellij eap getting unsupported operation exception 

### ISSUE THREAD

**Issue by greenhull** [mallowigi/material-theme-issues#451]
### Describe the bug

getting bug on ide startup

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:426)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:84)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:347)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:206)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:804)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:401)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:703)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:596)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:107)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:596)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:358)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1026)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1026)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:211)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:804)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Intellij level:

IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.10840.26, built on February 1, 2024
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: March 2, 2024
Runtime version: 21.0.2+13-b346.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=e0861f
  editor.focus.mode.color.dark=e0861f
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  idea.ignore.disabled.plugins=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  org.antlr.intellij.plugin (1.23)
  Gradle View (4.0.0)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties.bundle.editor (241.10840.7)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
  com.dubreuia.tool (2.6.2)
  com.zt.json-editor (2.9.1)
  String Manipulation (9.12.0)
  tarn.gradle.dependencies (1.6.2)
  GrepConsole (12.23.0-IJ2023.3)
  com.chylex.intellij.inspectionlens (1.3.1)
  PlantUML integration (7.5.1-IJ2023.2)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.gluonhq.plugin.intellij (2.8.6)
  MavenRunHelper (4.27.1-IJ2022.2)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  com.github.affishaikh.kotlinbuildergenerator (2.0.0)
  GradleDependenciesHelper (1.16)
  org.sonarlint.idea (10.3.0.77475)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.1.9+222)
  com.kn.diagrams.generator.generator (2022.2.0)
Kotlin: 241.10840.26-IJ

### To Reproduce

startup ide with latest material theme installed

### Expected behavior

clean startup

### Material Theme Version

8.23.3

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.10840.26, built on February 1, 2024
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: March 2, 2024
Runtime version: 21.0.2+13-b346.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=e0861f
  editor.focus.mode.color.dark=e0861f
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  idea.ignore.disabled.plugins=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  org.antlr.intellij.plugin (1.23)
  Gradle View (4.0.0)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties.bundle.editor (241.10840.7)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
  com.dubreuia.tool (2.6.2)
  com.zt.json-editor (2.9.1)
  String Manipulation (9.12.0)
  tarn.gradle.dependencies (1.6.2)
  GrepConsole (12.23.0-IJ2023.3)
  com.chylex.intellij.inspectionlens (1.3.1)
  PlantUML integration (7.5.1-IJ2023.2)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.gluonhq.plugin.intellij (2.8.6)
  MavenRunHelper (4.27.1-IJ2022.2)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  com.github.affishaikh.kotlinbuildergenerator (2.0.0)
  GradleDependenciesHelper (1.16)
  org.sonarlint.idea (10.3.0.77475)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.1.9+222)
  com.kn.diagrams.generator.generator (2022.2.0)
Kotlin: 241.10840.26-IJ
```

**Comment by mallowigi** [comment]
Hi, intellij EAP is not supported yet. Please stay in touch for updates

**Comment by The-Brit** [comment]
Would like to comment that this error also occurs on Webstorm 2023.3.4 (linux)

Details gleamed from about:

WebStorm 2023.3.4
Build #WS-233.14475.40, built on February 14, 2024
Licensed to Cherry Health / Mike Tomlinson
You have a perpetual fallback license for this version.
Subscription is active until February 21, 2025.
Runtime version: 21.0.2+13-LTS-58 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 6.7.4-2-manjaro
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 32
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=737374
  editor.focus.mode.color.dark=737374
  ide.new.editor.tabs.vertical.borders=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  atom-one (1.5.1)
  com.gmike.visual-studio-2019-dark (1.5.3)
  com.hiberbee.intellij.hiberbee-theme (2023.11.10.2029)
  Rider UI Theme Pack (0.14.11)
  monokai-pro (1.10)
  color.scheme.Tomorrow Dark (0.2)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  com.markskelton.one-dark-theme (5.10.0)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  ru.adelf.idea.dotenv (2024.1)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  com.github.dinbtechit.vscodetheme (1.10.10)
  com.brandiico.jetbrains-nightfall-theme (2.0.0)
  com.github.menwhorust.tomorrownighttheme (0.0.27)
  hu.aradipatrik.onedarknative (1.5)
Current Desktop: KDE

Exception on startup:

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.mallowigi.idea.utils.FieldHelper.makeNonFinal(FieldHelper.kt:52)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:64)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:426)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:84)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:347)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda$1(MTLafComponent.kt:79)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:101)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
