### ISSUE TITLE
[Bug]: Exception in Plugin Metrial Theme UI in IntelliJ

### ISSUE THREAD

**Issue by shaiu** [mallowigi/material-theme-issues#454]
### Describe the bug

Each time I open a project I get an Internal IDE error pop up

### To Reproduce

Just open a project and you get a error pop up

### Expected behavior

No exception

### Material Theme Version

8.13.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Licensed to RISKIFIED LTD / Shai Ungar
Subscription is active until October 1, 2024.
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=5a5d63
  editor.focus.mode.color.dark=5a5d63
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  net.sf.opk.avro-schema-support (221.4.1)
  com.github.copilot (1.4.15.4632)
  com.mallowigi (94.1.0)
  org.jetbrains.plugins.ruby (233.14475.28)
  org.jetbrains.plugins.go (233.14475.9)
  org.intellij.scala (2023.3.27)
  Pythonid (233.14475.28)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
Kotlin: 233.14475.28-IJ
```

### Logs/Screenshots

```shell
java.lang.Throwable: Icon https://riskified.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium has incorrect size: -1x-1
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.icons.IconUtilKt.checkIconSize(iconUtil.kt:347)
	at com.intellij.ui.svg.SvgKt$replaceCachedImageIcons$1.replaceIcon(svg.kt:370)
	at com.intellij.ui.DeferredIconImpl$DeferredIconAfterReplace.<init>(DeferredIconImpl.kt:354)
	at com.intellij.ui.DeferredIconImpl.replaceBy(DeferredIconImpl.kt:119)
	at com.intellij.ui.svg.SvgKt$replaceCachedImageIcons$1.replaceIcon(svg.kt:369)
	at com.intellij.ui.svg.SvgKt.replaceCachedImageIcons(svg.kt:375)
	at com.intellij.ui.svg.SvgKt.patchIconsWithColorPatcher(svg.kt:351)
	at com.intellij.ui.svg.SvgKt.access$patchIconsWithColorPatcher(svg.kt:1)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1$1.invoke(svg.kt:344)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1$1.invoke(svg.kt:343)
	at com.intellij.ui.svg.SvgKt$colorPatchedIcon$1.invoke$lambda$0(svg.kt:343)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58)
	at com.intellij.ui.svg.SvgKt.colorPatchedIcon(svg.kt:347)
	at com.intellij.ui.svg.SvgKt.paintIconWithSelection(svg.kt:320)
	at com.intellij.util.IconUtil.paintSelectionAwareIcon(IconUtil.kt:261)
	at com.intellij.ui.SimpleColoredComponent.paintIcon(SimpleColoredComponent.java:1088)
	at com.intellij.ui.SimpleColoredComponent.doPaintIcon(SimpleColoredComponent.java:800)
	at com.intellij.ui.SimpleColoredComponent.doPaint(SimpleColoredComponent.java:760)
	at com.intellij.ui.SimpleColoredComponent.paintComponent(SimpleColoredComponent.java:744)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:170)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintCell(BasicListUI.java:293)
	at com.mallowigi.idea.ui.MTListUI.paintCell(MTListUI.kt:132)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at com.mallowigi.idea.ui.MTListUI.paint(MTListUI.kt:69)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:189)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.components.JBList.paint(JBList.java:110)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5312)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:272)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5260)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5070)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:386)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by mallowigi** [comment]
duplicate
