### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zhangzf16** [mallowigi/material-theme-issues#464]
### Describe the bug

java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/config/application/MTConfig.getThemeFocusColor must not return null
	at com.mallowigi.idea.config.application.MTConfig.$$$reportNull$$$0(MTConfig.java)
	at com.mallowigi.idea.config.application.MTConfig.getThemeFocusColor(MTConfig.java:2109)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry.updateRegistry(MTRegistry.kt:61)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:354)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:443)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### To Reproduce

java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/config/application/MTConfig.getThemeFocusColor must not return null
	at com.mallowigi.idea.config.application.MTConfig.$$$reportNull$$$0(MTConfig.java)
	at com.mallowigi.idea.config.application.MTConfig.getThemeFocusColor(MTConfig.java:2109)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry.updateRegistry(MTRegistry.kt:61)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:354)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:443)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### Expected behavior

java.lang.IllegalStateException: @NotNull method com/mallowigi/idea/config/application/MTConfig.getThemeFocusColor must not return null
	at com.mallowigi.idea.config.application.MTConfig.$$$reportNull$$$0(MTConfig.java)
	at com.mallowigi.idea.config.application.MTConfig.getThemeFocusColor(MTConfig.java:2109)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry$colorEntries$1.invoke(MTRegistry.kt:48)
	at com.mallowigi.idea.utils.MTRegistry.updateRegistry(MTRegistry.kt:61)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:354)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:291)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:309)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:122)
	at com.mallowigi.idea.MTLafComponent.initComponent$lambda$3(MTLafComponent.kt:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:443)
	at com.mallowigi.idea.MTLafComponent.initComponent(MTLafComponent.kt:147)
	at com.mallowigi.idea.MTLafComponent.appFrameCreated$lambda$0(MTLafComponent.kt:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### Material Theme Version

3.4

### IDE

IntelliJ IDEA

**Comment by zhangzf16** [comment]
When's the fix?

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-issues/issues/426

**Comment by mallowigi** [comment]
Please follow the solution described in the thread
