### ISSUE TITLE
[Bug]: IntelliJ Settings screen won't open when Python plugin enabled

### ISSUE THREAD

**Issue by daviddenton** [mallowigi/material-theme-issues#472]
### Describe the bug

Attempting to open the IDE settings menu with `CMD+,` does nothing - an error is generated in the log file: 

### To Reproduce

1. Enable python plugin
2. Enable material theme plugin
3. Attempt to open the settings menu with `cmd+,'
4. The panel fails to open and the intellij IDE error icon (bottom right) flashes.
5. Click on the error icon to open and see the exception

### Expected behavior

The settings panel opens! :)

### Material Theme Version

v9.0.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2024.1 RC (Ultimate Edition)
Build #IU-241.14494.158, built on March 21, 2024
Licensed to http4k / David Denton
Subscription is active until May 17, 2024.
For non-commercial open source development only.
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  debugger.new.tool.window.layout=true
  documentation.show.toolbar=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.10.0)
  PlantUML integration (7.7.1-IJ2023.2)
  org.plugin.dot.id (1.5.3)
  DevKit (241.14494.180)
  com.arcticicestudio.nord.jetbrains (0.13.0)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.4)
  org.intellij.plugins.hcl (241.14494.150)
  hu.hawser.co-author-plugin (2.3)
  com.jetbrains.darkPurpleTheme (1.3)
  org.mvnsearch.plugins.justPlugin (0.4.3)
  com.intellij.mermaid (0.0.20+IJ.232)
  org.asciidoctor.intellij.asciidoc (0.41.11)
  net.ashald.envfile (3.4.2)
  com.github.copilot (1.5.0.5148)
  com.mallowigi (95.0.0)
  com.chrisrm.idea.MaterialThemeUI (9.0.0)
  com.github.s4nchez.okeydoke.idea (0.6.2)
  com.dmarcotte.handlebars (241.14494.150)
  com.github.hugohomesquita.htmxjetbrains (0.0.9)
  org.jetbrains.settingsRepository (241.14494.150)
Kotlin: 241.14494.158-IJ
```

### Logs/Screenshots

```shell
2024-03-23 17:34:11,323 [ 107100] SEVERE - #c.i.o.o.e.ConfigurableWrapper - IntelliJ IDEA 2024.1 RC  Build #IU-241.14494.158
2024-03-23 17:34:11,323 [ 107100] SEVERE - #c.i.o.o.e.ConfigurableWrapper - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-03-23 17:34:11,324 [ 107101] SEVERE - #c.i.o.o.e.ConfigurableWrapper - OS: Mac OS X
2024-03-23 17:34:11,324 [ 107101] SEVERE - #c.i.o.o.e.ConfigurableWrapper - Plugin to blame: Material Theme UI version: 9.0.0
2024-03-23 17:34:11,324 [ 107101] SEVERE - #c.i.o.o.e.ConfigurableWrapper - Last Action: Run
2024-03-23 17:34:11,419 [ 107196]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.MicroservicesUiBundle
2024-03-23 17:34:11,419 [ 107196]   INFO - #c.i.i.p.PluginManager - Cannot find plugin com.intellij.microservices.ui resource-bundle: messages.MicroservicesUiBundle
2024-03-23 17:34:11,420 [ 107197]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.DockerGatewayBundle
2024-03-23 17:34:11,420 [ 107197]   INFO - #c.i.i.p.PluginManager - Cannot find plugin org.jetbrains.plugins.docker.gateway resource-bundle: messages.DockerGatewayBundle
2024-03-23 17:34:11,421 [ 107198]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.SvnBundle
2024-03-23 17:34:11,421 [ 107198]   INFO - #c.i.i.p.PluginManager - Cannot find plugin Subversion resource-bundle: messages.SvnBundle
2024-03-23 17:34:11,421 [ 107198]   INFO - #c.i.AbstractBundle - Cannot load resource bundle from *.properties file, falling back to slow class loading: messages.VueBundle
2024-03-23 17:34:11,422 [ 107199]   INFO - #c.i.i.p.PluginManager - Cannot find plugin org.jetbrains.plugins.vue resource-bundle: messages.VueBundle
2024-03-23 17:34:11,423 [ 107200] SEVERE - #c.i.i.a.ShowSettingsUtilImpl - Could not initialize class com.mallowigi.idea.annotators.settings.PythonColorSettingsKt
java.lang.NoClassDefFoundError: Could not initialize class com.mallowigi.idea.annotators.settings.PythonColorSettingsKt
	at com.mallowigi.idea.annotators.settings.PythonColorSettings.getAttributeDescriptors(PythonColorSettings.kt:44)
	at com.intellij.application.options.colors.ColorSettingsUtil.getAllAttributeDescriptors(ColorSettingsUtil.java:41)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getDescriptorImpl(ColorSettingsPagesImpl.java:56)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getAttributeDescriptor(ColorSettingsPagesImpl.java:40)
	at com.intellij.application.options.colors.ColorAndFontOptions$SchemeTextAttributesDescription.<init>(ColorAndFontOptions.java:879)
	at com.intellij.application.options.colors.ColorAndFontOptions.initDescriptions(ColorAndFontOptions.java:663)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:622)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:611)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:584)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:451)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:307)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.buildChildren(SettingsTreeView.java:562)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:26)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:12)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:53)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:68)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:68)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:48)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:40)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:31)
	at com.intellij.ui.tree.FilteringTreeModel.createModel(FilteringTreeModel.java:26)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:201)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:92)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:189)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:68)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.kt:39)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.getDialog(ShowSettingsUtilImpl.kt:33)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.kt:104)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:61)
	at com.intellij.ui.mac.MacOSApplicationProviderKt$initMacApplication$2$1.invoke(MacOSApplicationProvider.kt:64)
	at com.intellij.ui.mac.MacOSApplicationProviderKt$initMacApplication$2$1.invoke(MacOSApplicationProvider.kt:63)
	at com.intellij.ui.mac.MacOSApplicationProviderKt$submit$2.invokeSuspend(MacOSApplicationProvider.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:123)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ExceptionInInitializerError: Exception com.intellij.diagnostic.PluginException: Class com.jetbrains.python.highlighting.PyHighlighter must not be requested from main classloader of Pythonid plugin. Matches content module (packagePrefix=com.jetbrains.python., moduleName=intellij.python.community.impl). [in thread "AWT-EventQueue-0"]
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:203)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.mallowigi.idea.annotators.settings.PythonColorSettingsKt.<clinit>(PythonColorSettings.kt:96)
	at com.mallowigi.idea.annotators.settings.PythonColorSettings.getAttributeDescriptors(PythonColorSettings.kt:44)
	at com.intellij.application.options.colors.ColorSettingsUtil.getAllAttributeDescriptors(ColorSettingsUtil.java:41)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getDescriptorImpl(ColorSettingsPagesImpl.java:56)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:174)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:40)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getAttributeDescriptor(ColorSettingsPagesImpl.java:40)
	at com.intellij.application.options.colors.ColorAndFontOptions$SchemeTextAttributesDescription.<init>(ColorAndFontOptions.java:879)
	at com.intellij.application.options.colors.ColorAndFontOptions.initDescriptions(ColorAndFontOptions.java:663)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:622)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:611)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:584)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:451)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:75)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:307)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:148)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:157)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:110)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:119)
	at com.intellij.ide.actions.ShowSettingsUtilImpl$Companion.getConfigurableGroups(ShowSettingsUtilImpl.kt:48)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.kt)
	... 49 more
```

**Comment by mallowigi** [comment]
Thanks. Fixing it for version 9.1.0
