### ISSUE TITLE
[Bug]: Many error on interacting UML Diagram

### ISSUE THREAD

**Issue by qsef1256** [mallowigi/material-theme-issues#473]
### Describe the bug

12~120 error appeared on interacting UML diagram

It is impossible to upload all logs because dozens of types of errors occur, and the errors seem to be different for each UML.

### To Reproduce

1. Show Diagram
2. Interacting with Diagram (Click Field, Constructors, etc...)
3. See Error (Occurrence conditions seems irregular.)

### Expected behavior

error should not appear.

### Material Theme Version

v8.13.2

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Licensed to
Subscription is active until May 3, 2024.
For educational use only.
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=777777
  editor.focus.mode.color.dark=777777
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.github.lppedd.idea-conventional-commit (0.22.0)
  com.github.leomillon.uuidgenerator (4.5.1)
  Quick Notes (3.3)
  Batch Scripts Support (1.0.13)
  com.nasller.CodeGlancePro (1.8.2)
  com.checkmarx.checkmarx-ast-jetbrains-plugin (2.0.11)
  com.jetbrains.space (233.15026.16)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  Statistic (4.2.14)
  com.tabnine.TabNine (1.68.0)
  de.santiv.fastscrolling (1.2)
  com.intellij.grazie.pro (0.3.294)
  com.tabbyml.intellij-tabby (1.4.0)
  software.xdev.saveactions (1.1.1)
  com.euphoricity.gitignore (0.3)
  com.intellij.guice (233.11799.196)
  Builder Generator (1.4.0)
  com.jetbrains.jax.ws (233.13135.65)
  com.intellij.spring.shell (233.11799.196)
  String Manipulation (9.12.0)
  CheckStyle-IDEA (5.89.1)
  com.intellij.javaee.ejb (233.11799.196)
  tarn.gradle.dependencies (1.6.2)
  MavenRunHelper (4.27.1-IJ2022.2)
  com.intellij.ml.llm (233.15026.9)
  com.demonwav.minecraft-dev (2023.3-1.7.3)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  com.jetbrains.packagesearch.intellij-plugin (233.11800.8)
  com.haulmont.jpab (2023.4.1-233)
  com.dmarcotte.handlebars (233.11799.172)
  com.intellij.tide (233.15026.17)
  org.sonarlint.idea (10.4.1.77998)
  me.rerere.discord-ij (1.0.11)
  mobi.hsz.idea.gitignore (4.5.2)
  com.alexandermalcin.browser (1.0.7)
  cn.yiiguxing.plugin.translate (3.5.7)
Kotlin: 233.15026.9-IJ
```

### Logs/Screenshots

![image](https://github.com/mallowigi/material-theme-issues/assets/44014066/5204e1f8-6321-44ea-b191-bb0abde8ded8)
[threadDump.txt](https://github.com/mallowigi/material-theme-issues/files/14815178/threadDump.txt)

```shell


com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[AWT-EventQueue-0,6,main] 1746986380 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:421)
	at com.intellij.psi.impl.source.tree.CompositeElement.getChildrenAsPsiElements(CompositeElement.java:403)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceParameterListImpl.getTypeParameterElements(PsiReferenceParameterListImpl.java:39)
	at com.intellij.psi.impl.PsiImplUtil.typesByReferenceParameterList(PsiImplUtil.java:237)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceParameterListImpl.getTypeArguments(PsiReferenceParameterListImpl.java:58)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getTypeParameters(PsiJavaCodeReferenceElementImpl.java:1049)
	at com.intellij.psi.impl.source.resolve.JavaResolveUtil$1.getSubstitutor(JavaResolveUtil.java:276)
	at com.intellij.psi.impl.source.PsiClassReferenceType$DelegatingClassResolveResult.getSubstitutor(PsiClassReferenceType.java:134)
	at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:844)
	at com.intellij.psi.util.PsiUtil.equalOnEquivalentClasses(PsiUtil.java:680)
	at com.intellij.psi.PsiClassType.equals(PsiClassType.java:106)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:32)
	at com.intellij.psi.util.PsiUtil.equalOnEquivalentClasses(PsiUtil.java:701)
	at com.intellij.psi.util.PsiUtil.equalOnEquivalentClasses(PsiUtil.java:685)
	at com.intellij.psi.PsiClassType.equals(PsiClassType.java:106)
	at java.base/java.util.Objects.equals(Objects.java:64)
	at com.intellij.uml.java.JavaProperty.equals(JavaProperty.java:259)
	at java.base/java.util.HashMap.getNode(HashMap.java:570)
	at java.base/java.util.HashMap.get(HashMap.java:556)
	at com.intellij.uml.java.JavaUmlNodeItems.getItemData(JavaUmlNodeItems.java:85)
	at com.intellij.uml.java.JavaUmlNodeItems.getItemType(JavaUmlNodeItems.java:56)
	at com.intellij.uml.java.JavaUmlDataModel.getItemType(JavaUmlDataModel.java:1012)
	at com.intellij.uml.java.JavaUmlElementManager.getItemType(JavaUmlElementManager.java:580)
	at com.intellij.uml.java.JavaUmlElementManager.getItemType(JavaUmlElementManager.java:67)
	at com.intellij.diagram.components.DiagramNodeItemComponent.setUpText(DiagramNodeItemComponent.java:97)
	at com.intellij.diagram.components.DiagramNodeItemComponent.setUp(DiagramNodeItemComponent.java:67)
	at com.intellij.diagram.components.DiagramNodeBodyComponent.getListCellRendererComponent(DiagramNodeBodyComponent.java:178)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.mallowigi.idea.ui.MTListUI.paintCell(MTListUI.kt:111)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:383)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:306)
	at com.mallowigi.idea.ui.MTListUI.paint(MTListUI.kt:69)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:189)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.components.JBList.paint(JBList.java:110)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at com.intellij.diagram.components.DiagramNodeContainer.doPaintComponent(DiagramNodeContainer.java:273)
	at com.intellij.diagram.components.DiagramNodeContainer$MyRenderCacheHandler.fillRenderCache(DiagramNodeContainer.java:489)
	at com.intellij.diagram.components.DiagramNodeContainer$MyRenderCacheHandler.computeUpToDateCacheIfPossible(DiagramNodeContainer.java:451)
	at com.intellij.diagram.components.DiagramNodeContainer$MyRenderCacheHandler.lambda$getRenderCache$1(DiagramNodeContainer.java:361)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at com.intellij.diagram.components.DiagramNodeContainer$MyRenderCacheHandler.getRenderCache(DiagramNodeContainer.java:360)
	at com.intellij.diagram.components.DiagramNodeContainer$MyRenderCacheHandler.paint(DiagramNodeContainer.java:414)
	at com.intellij.diagram.components.DiagramNodeContainer.paint(DiagramNodeContainer.java:224)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at com.intellij.openapi.graph.impl.view.FastNodeCellRendererPainter.paintNode(FastNodeCellRendererPainter.java:55)
	at z.m.kJ.B(Unknown Source)
	at z.m.kJ.z(Unknown Source)
	at z.m.M3.paint(Unknown Source)
	at z.m.zC.z(Unknown Source)
	at z.m.ni.B(Unknown Source)
	at z.m.zC.B(Unknown Source)
	at z.m.zC.z(Unknown Source)
	at z.m.HI.H(Unknown Source)
	at z.m.HI.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at com.intellij.uml.components.UmlGraphZoomableViewport.paint(UmlGraphZoomableViewport.java:87)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at com.intellij.openapi.fileEditor.impl.EditorTabs.paintChildren(EditorTabbedContainer.kt:613)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1101)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3988)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.paint(IdeFrameImpl.kt:123)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:893)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:386)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
```

**Comment by mallowigi** [comment]
This has been fixed in 2024.1, I suppose. Try to upgrade and tell me if it reproduces.
