### ISSUE TITLE
[Feature]: Synchronization theme configuration suddenly interrupted resulting in an error

### ISSUE THREAD

**Issue by aihu2020** [mallowigi/material-theme-issues#525]
### Describe the feature

Hello boss, may I ask if I interrupted the process when synchronizing the theme configuration, resulting in an error after entering idea. After deleting the Material Theme UI plug-in from the plugins folder in idea, it can start normally. If you reinstall this plug-in, you will still report an error. How to delete the theme configuration or use the plug-in again without reinstalling idea? The following is the error report：

Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.RuntimeException: Cannot invoke (class=MTLafComponent, method=appStarted, topic=AppLifecycleListener)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:676)
    at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:422)
    at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:401)
    at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
    at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:460)
    at jdk.proxy1/jdk.proxy1.$Proxy55.appStarted(Unknown Source)
    at com.intellij.idea.IdeStarter$start$2.invokeSuspend(IdeStarter.kt:74)
    at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
    at com.intellij.idea.IdeStarter$start$2.invoke(IdeStarter.kt)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
    at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
    at com.intellij.idea.IdeStarter.start$suspendImpl(IdeStarter.kt:66)
    at com.intellij.idea.IdeStarter.start(IdeStarter.kt)
    at com.intellij.ide.bootstrap.ApplicationLoader.initApplicationImpl(ApplicationLoader.kt:90)
    at com.intellij.ide.bootstrap.ApplicationLoader$initApplicationImpl$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'str' of com/intellij/ui/ColorUtil.fromHex must not be null
    at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:131)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:471)
    at com.mallowigi.idea.MTLafComponent.appStarted(MTLafComponent.kt:76)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:696)
    at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:663)
    ... 20 more
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'str' of com/intellij/ui/ColorUtil.fromHex must not be null
    at com.intellij.ui.ColorUtil.$$$reportNull$$$0(ColorUtil.java)
    at com.intellij.ui.ColorUtil.fromHex(ColorUtil.java)
    at com.mallowigi.idea.themes.themes.MTAbstractTheme.applyAccentMode(MTAbstractTheme.kt:361)
    at com.mallowigi.idea.MTThemeManager.applyAccentMode(MTThemeManager.kt:425)
    at com.mallowigi.idea.MTThemeManager.applyAccents(MTThemeManager.kt:395)
    at com.mallowigi.idea.themes.themes.MTAbstractTheme.activate(MTAbstractTheme.kt:182)
    at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:324)
    at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:288)
    at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:311)
    at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:121)
    at com.mallowigi.idea.MTLafComponent.appStarted$lambda$1(MTLafComponent.kt:78)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
    at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
    at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:100)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
    at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
    at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
    at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

-----
Your JRE: 17.0.9+7-b1000.46 aarch64 (JetBrains s.r.o.)
/Applications/IntelliJ IDEA.app/Contents/jbr/Contents/Home

### Material Theme Version

8.12.6

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
授权给 signup scooter
您有此版本的永久回退许可证。
订阅有效期至 2025年8月1日。
Runtime version: 17.0.9+7-b1000.46 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.zh (232.172)
    co.notime.intellijPlugin.backgroundImagePlus (1.2.1)
    com.intellij.ml.llm (232.9826)
    JRebelPlugin (2023.4.1)
    MavenRunHelper (4.26.0-IJ2022.2)
    Pythonid (232.10227.8)
    com.alibabacloud.intellij.cosy (1.0.1)
    com.mallowigi (93.1.0)
    zielu.gittoolbox (500.0.18+222)
    com.baomidou.plugin.idea.mybatisx (1.6.0)
    cn.yiiguxing.plugin.translate (3.5.4)

Kotlin: 232-1.9.0-IJ10227.8
```

**Comment by mallowigi** [comment]
This version is not supported anymore.
