### ISSUE TITLE
Prepare for JBR17, stop using Field modifications.

### ISSUE THREAD

**Issue by jvthert** [mallowigi/material-theme-issues#66]
### Summary

Jetbrains is currently developing JBR17, which will probably become the standard JBR to run the Jetbrains IDE's this year. It makes a massive difference for MacOS users because it supports Metal 2d rendering and makes the IDE a lot faster.

The current version of Material Theme for Jetbrains relies on messing with fields using reflection. It has been made a lot harder, and the current approach is not supported anymore since Java 12. For this reason, the plugin crashes when running under JBR 17

A possible workaround if this is required is [described here](https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12).

### Expected behavior

The look and feel we all expect and no errors. And (especially on Macs) a much more responsive IDE with clean font rendering.

### Actual behavior
<details>
  <summary>Most of the good stuff but Material breaks with a stacktrace caused by a NoSuchFieldException</summary>

```
java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.mallowigi.idea.utils.StaticPatcher.setFinalStatic(StaticPatcher.kt:67)
	at com.mallowigi.idea.UIReplacer.patchCompletionPopup(UIReplacer.kt:342)
	at com.mallowigi.idea.UIReplacer.patchUI(UIReplacer.kt:92)
	at com.mallowigi.idea.MTThemeManager.activate(MTThemeManager.kt:364)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:310)
	at com.mallowigi.idea.MTThemeManager.activateLAF(MTThemeManager.kt:328)
	at com.mallowigi.idea.MTLafComponent.activateLaf(MTLafComponent.kt:115)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda-0(MTLafComponent.kt:73)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:777)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:747)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at com.intellij.cloudConfig.CloudConfigManager.waitDone(CloudConfigManager.java:1857)
	at com.intellij.cloudConfig.CloudConfigManager.getRepositoryPlugins(CloudConfigManager.java:1826)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$updatePlugins$43(CloudConfigManager.java:1929)
	at com.intellij.cloudConfig.CloudConfigManager.mergePlugins(CloudConfigManager.java:2099)
	at com.intellij.cloudConfig.CloudConfigManager.mergePlugins(CloudConfigManager.java:2090)
	at com.intellij.cloudConfig.CloudConfigManager.updatePlugins(CloudConfigManager.java:1925)
	at com.intellij.cloudConfig.CloudConfigManager.safeUpdatePlugins(CloudConfigManager.java:1866)
	at com.intellij.cloudConfig.CloudConfigManager.lambda$doConnection$20(CloudConfigManager.java:1005)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:777)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:747)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

### Steps to reproduce (if needed)

1. Download the version of JBR17 for your os and extract it. Download it [from GitHub](https://github.com/JetBrains/JetBrainsRuntime/releases?q=17_)
2. Change the boot JVM for IntelliJ and set it to a JBR17 build. More details [can be found here](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)
3. Add required [custom JVM options](https://www.jetbrains.com/help/idea/tuning-the-ide.html#configure-jvm-options) and reboot the IDE.
    ```
    -Dsun.java2d.metal=true
    --add-opens=java.desktop/java.awt.event=ALL-UNNAMED
    --add-opens=java.desktop/sun.font=ALL-UNNAMED
    --add-opens=java.desktop/java.awt=ALL-UNNAMED
    --add-opens=java.desktop/sun.awt=ALL-UNNAMED
    --add-opens=java.base/java.lang=ALL-UNNAMED
    --add-opens=java.base/java.util=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing=ALL-UNNAMED
    --add-opens=java.desktop/sun.swing=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
    --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
    --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
    --add-exports=java.desktop/sun.font=ALL-UNNAMED
    --add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED
    --add-exports=java.desktop/com.apple.laf=ALL-UNNAMED
    --add-exports=java.desktop/com.apple.eawt.event=ALL-UNNAMED
    ```

### Environment

This is a Java interoperability issue, not a Jetbrains thing.
Any Jetbrains IDE, any OS, any version of this plugin running with the new JBR17

**Comment by mallowigi** [comment]
Thanks for the heads up, is there an ETA for this?

**Comment by jvthert** [comment]
I think they are (or were) planning for the next major release: https://youtrack.jetbrains.com/issue/JBR-3729

However, given the progress I'd expect it to be 2022.2 🤷‍♂️

**Comment by jvthert** [comment]
I would not mind lending a hand. I think it should be possible to fix it by only updating the `StaticPatcher`.

**Comment by mallowigi** [comment]
Do you have experience doing so? I can add you as a contributor if you want.

**Comment by jvthert** [comment]
I've been coding Java, Scala, and Python professionally for the past 15 years. I'm not looking to become a full-time contributor, but this is an interesting issue, and I'm not too fond of the error I get every time I start my IDE now. So I'd love to help. I'll send you a message on LinkedIn to know who I am.

**Comment by mallowigi** [comment]
Too slow @jvthert, I finally fixed it! But thanks for the help on finding the workaround, you're the best!
