### ISSUE TITLE
[Bug]: Error thrown on launch v7.0.0 + PHPStorm 2022.1: IllegalStateException: TextAttributeKey

### ISSUE THREAD

**Issue by pgnd** [mallowigi/material-theme-issues#80]
### Describe the bug

On PHPStorm Launch, apparently non-fatal error is throws, atrributed to MaterialThemeUI

### To Reproduce

Install PHPStorm
Install MaterialThemeUI
(re)Lauch PHPStorm

### Expected behavior

no error on launch

### Material Theme Version

v7.0.0

### IDE

PHPStorm

### System Info

```
PhpStorm 2022.1 EAP
Build #PS-221.4165.156, built on February 10, 2022
...
Expiration date: March 12, 2022
Runtime version: 11.0.14+9-b1982.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.7-200.fc35.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    run.processes.with.pty=TRUE
    performance.watcher.unresponsive.interval.ms=0
    documentation.show.toolbar=true
    ide.tooltip.initialDelay=58
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.27.0)
    String Manipulation (8.26.203.5981.1)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (7.0.0)
    ru.adelf.idea.dotenv (2022.1)
    com.laravel_idea.plugin (5.1.0.221)

Current Desktop: Undefined
```

### Logs/Screenshots
```
java.lang.IllegalStateException: TextAttributeKey(name:'TS.ENUM', fallbackAttributeKey:'TS.KEYWORD (fallbackKey: JS.KEYWORD (fallbackKey: DEFAULT_KEYWORD))')  was already registered with the other fallback attribute key: TS.CLASS (fallbackKey: DEFAULT_CLASS_NAME (fallbackKey: DEFAULT_IDENTIFIER (fallbackKey: TEXT)))
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:226)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:212)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:212)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:199)
	at com.mallowigi.idea.annotators.TSAnnotator.<clinit>(TSAnnotator.kt:84)
	at com.mallowigi.idea.annotators.settings.TSColorSettings.<clinit>(TSColorSettings.kt:63)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.kt:80)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:91)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:474)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:266)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:33)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:538)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:530)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:514)
	at com.intellij.application.options.colors.ColorAndFontOptions.resetImpl(ColorAndFontOptions.java:639)
	at com.intellij.application.options.colors.ColorAndFontOptions.reset(ColorAndFontOptions.java:651)
	at com.mallowigi.idea.MTThemeManager.resetColorScheme(MTThemeManager.kt:734)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda-0(MTLafComponent.kt:71)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:802)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:432)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:598)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:478)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
```

**Comment by ddnexus** [comment]
It might be connected, or it might be affect also the Large Tool Windows that does not work anymore. It is shown as ON and the menu cannot be disabled, but it does not work either ways.

**Comment by mallowigi** [comment]
I have stopped working on the EAP for now. Sorry but I am in the middle of a big remake of the UI at the time so please stay on RC or use the currently flawed version for now.
