### ISSUE TITLE
[Bug]: java.lang.IllegalStateException: TextAttributeKe

### ISSUE THREAD

**Issue by jmatias** [mallowigi/material-theme-issues#86]
### Describe the bug

java.lang.IllegalStateException: TextAttributeKey(name:'TS.ENUM', fallbackAttributeKey:'TS.KEYWORD (fallbackKey: JS.KEYWORD (fallbackKey: DEFAULT_KEYWORD))')  was already registered with the other fallback attribute key: TS.CLASS (fallbackKey: DEFAULT_CLASS_NAME (fallbackKey: DEFAULT_IDENTIFIER (fallbackKey: TEXT)))
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:226)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:212)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:212)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:199)
	at com.mallowigi.idea.annotators.TSAnnotator.<clinit>(TSAnnotator.kt:84)
	at com.mallowigi.idea.annotators.settings.TSColorSettings.<clinit>(TSColorSettings.kt:63)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:482)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:845)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.kt:80)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:91)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:474)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:266)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:35)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:33)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:538)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:530)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:514)
	at com.intellij.application.options.colors.ColorAndFontOptions.resetImpl(ColorAndFontOptions.java:639)
	at com.intellij.application.options.colors.ColorAndFontOptions.reset(ColorAndFontOptions.java:651)
	at com.mallowigi.idea.MTThemeManager.resetColorScheme(MTThemeManager.kt:734)
	at com.mallowigi.idea.MTLafComponent.appStarted$lambda-0(MTLafComponent.kt:71)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:802)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### To Reproduce

Exception occurs immediately after the IDE starts.

### Expected behavior

No exceptions

### Material Theme Version

v7.0.0

### IDE

IntelliJ IDEA

### System Info

```shell
IntelliJ IDEA 2022.1 EAP (Ultimate Edition)
Build #IU-221.4501.155, built on February 17, 2022
Licensed to IntelliJ IDEA EAP user: Javier Matias
Expiration date: March 19, 2022
Runtime version: 11.0.14+9-b1993.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 12
Registry:
    actionSystem.cache.data=false
    ide.mac.transparentTitleBarAppearance=false
    ide.balloon.shadow.size=0
    ide.images.show.chessboard=true
    go.run.processes.with.pty=false
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    some.awesome (1.14)
    org.jetbrains.plugins.rest (221.4501.155)
    org.jetbrains.plugins.go-template (221.4501.155)
    org.jetbrains.plugins.go (221.4501.155)
    net.seesharpsoft.intellij.plugins.csv (2.18.2)
    name.kropp.intellij.makefile (221.4501.155)
    de.netnexus.camelcaseplugin (3.0.12)
    com.toan2.yapf (1.2)
    com.jetbrains.plugins.ini4idea (221.4501.155)
    com.intellij.plugins.macoskeymap (221.4501.155)
    com.intellij.nativeDebug (221.4501.155)
    org.jetbrains.plugins.ruby (221.4501.155)
    com.intellij.properties.bundle.editor (221.4501.160)
    org.jetbrains.jumpToLine (0.1.8)
    com.intellij.guice (221.4501.155)
    com.github.shiraji.ccch (1.0.1)
    com.github.leomillon.uuidgenerator (4.5.1)
    Shifter (1.9.6)
    Keymap exporter (2.2)
    com.microsoft.vso.idea (1.162.0)
    com.mallowigi (60.0.0)
    FrameSwitcher (3.29.0-212)
    com.intellij.kubernetes (221.4501.155)
    Pythonid (221.4501.155)
    ru.adelf.idea.dotenv (2022.1)
    zielu.gittoolbox (212.8.6)
    org.intellij.scala (2022.1.4)
    izhangzhihao.rainbow.brackets (6.21)
    com.intellij.bigdatatools (221.4165.24)
    com.chrisrm.idea.MaterialThemeUI (7.0.0)
    lermitage.intellij.extra.icons (1.69.3.203)

Kotlin: 221-1.6.20-M1-release-207-IJ4501.155
```

**Comment by mallowigi** [comment]
duplicate

**Comment by jmatias** [comment]
@mallowigi Could you provide the link to the duplicated issue? I'd like to track it.

**Comment by jmatias** [comment]
> @mallowigi Could you provide the link to the duplicated issue? I'd like to track it.

Found it.  Nevermind

https://github.com/mallowigi/material-theme-issues/issues/80
